delete from LRP_EVENT_WORKSCOPE;
delete from TASK_DEFN;

-- INSERTING into TASK_DEFN
Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,23293,1,0,0,to_date('31-AUG-04','DD-MON-RR'),to_date('31-AUG-04','DD-MON-RR'),4650,'MASTER_MATRIX');

-- INSERTING into TASK_TASK
Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 23293, null, null, 4650, 23293, 10, 'SRVC', null, null, 8000000, 'A320', 229, null, null, null, null, null, null, null, 0, 'ACTV', 0, 76, 'CREATE_14', 'Test child-task creation logic', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 0, null, 0, 0, 'NA', 1, null, null, null, 0, 1, 0, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, 0, 0, 0, null, null, null, null, null, 0, to_date('30-APR-02', 'DD-MON-RR'), to_date('06-MAR-08', 'DD-MON-RR'), 4650, 'MX0803_MASTER');

-- INSERTING into TASK_DEFN
Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID, LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1785,4650,1785,4650,4,4650,23293,4650,23293,0,21,to_date('22-FEB-15','DD-MON-RR'),1,0,100,null,null,4650,1786,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID, LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1786,4650,1786,4650,4,4650,23293,4650,23293,0,21,to_date('20-JUN-27','DD-MON-RR'),1,0,100,null,null,4650,1787,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1787,4650,1787,4650,4,4650,23293,4650,23293,0,21,to_date('16-AUG-09','DD-MON-RR'),1,0,100,null,null,4650,1788,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1788,4650,1788,4650,4,4650,23293,4650,23293,0,21,to_date('12-JUL-09','DD-MON-RR'),1,0,100,null,null,4650,1789,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1789,4650,1789,4650,4,4650,23293,4650,23293,0,21,to_date('04-JUN-23','DD-MON-RR'),1,0,100,null,null,4650,1790,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1790,4650,1790,4650,4,4650,23293,4650,23293,0,21,to_date('16-JUL-17','DD-MON-RR'),1,0,100,null,null,4650,1791,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1791,4650,1791,4650,4,4650,23293,4650,23293,0,21,to_date('23-JAN-28','DD-MON-RR'),1,0,100,null,null,4650,1792,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1792,4650,1792,4650,4,4650,23293,4650,23293,0,21,to_date('23-JUL-23','DD-MON-RR'),1,0,100,null,null,4650,1793,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_EVENT_WORKSCOPE (LRP_EVENT_DB_ID,LRP_EVENT_ID,LRP_WORKSCOPE_DB_ID, LRP_WORKSCOPE_ID,LRP_DB_ID,LRP_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,RULE_TASK_DB_ID,RULE_TASK_ID,RULE_DATA_TYPE_DB_ID,RULE_DATA_TYPE_ID,DEADLINE_DT,DRIVER_BOOL,MAN_HOURS,YIELD_PCT,SCHED_DB_ID,SCHED_ID,PREV_WORKSCOPE_DB_ID, PREV_WORKSCOPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1793,4650,1793,4650,4,4650,23293,4650,23293,0,21,to_date('19-MAY-19','DD-MON-RR'),1,0,100,null,null,4650,1785,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

-- INSERTING into TASK_WORK_TYPE
Insert into TASK_WORK_TYPE (TASK_DB_ID, TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values(4650, 23293,10,'ADMIN');

