/********************************************
** INSERT SCRIPT FOR TABLE "REF_WF_STEP_REASON"
** 10-Level
** DATE: 28-OCT-2008 TIME: 00:00:00
*********************************************/

INSERT INTO REF_WF_PRIORITY (WF_PRIORITY_DB_ID, WF_PRIORITY_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'HIGH', 'HIGH', 'HIGH PRIORITY', 0, '28-OCT-08', '28-OCT-08', 0, 'MXI');

INSERT INTO REF_WF_PRIORITY (WF_PRIORITY_DB_ID, WF_PRIORITY_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'MED', 'MEDIUM', 'MEDIUM PRIORITY', 0, '28-OCT-08', '28-OCT-08', 0, 'MXI');

INSERT INTO REF_WF_PRIORITY (WF_PRIORITY_DB_ID, WF_PRIORITY_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'LOW', 'LOW', 'LOW PRIORITY', 0, '28-OCT-08', '28-OCT-08', 0, 'MXI');