/********************************************
** INSERT SCRIPT FOR TABLE "REF_PART_PROVIDER_TYPE"
** 10-Level
** DATE: 18-OCT-07
*********************************************/
INSERT INTO REF_PART_PROVIDER_TYPE (PART_PROVIDER_TYPE_DB_ID, PART_PROVIDER_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'MROPROV', 'MRO-provided', null, 0, '18-OCT-2007', '18-OCT-2007', 10, 'MXI');

INSERT INTO REF_PART_PROVIDER_TYPE (PART_PROVIDER_TYPE_DB_ID, PART_PROVIDER_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'CUSTPAID', 'Customer-paid', null, 0, '18-OCT-2007', '18-OCT-2007', 10, 'MXI');

INSERT INTO REF_PART_PROVIDER_TYPE (PART_PROVIDER_TYPE_DB_ID, PART_PROVIDER_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'CUSTPROV', 'Customer-provided', null, 0, '18-OCT-2007', '18-OCT-2007', 10, 'MXI');