/********************************************
** INSERT SCRIPT FOR TABLE "REF_QTY_UNIT"
** 10-Level
** DATE: 09/22/2004 TIME: 00:00:00
*********************************************/
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'L', 'Liter', 'Quantity unit for liquids', 1, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GAL', 'Gallon', 'Quantity unit for liquids', 1, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'QRT', 'Quart', 'Quantity unit for liquids', 1, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BOX', 'Box', 'Quantity for inventory that is tracked in bulk', 0, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BAG', 'Bag', 'Quantity for inventory that is tracked in bulk', 0, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ROLL', 'Roll', 'Quantity for tape inventory', 0, null, null, 0, to_date('01-10-2004', 'dd-mm-yyyy'), to_date('01-10-2004', 'dd-mm-yyyy'), 0, 'kramer_master');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'AA', 'Two Hundred, Fifty', '250 each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'AM', 'Ampoule', 'A small glass or plastic tube sealed by fusion after filling.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'AT', 'Assortment', 'A collection of various items falling into a common category or class and packaged as a small unit constituting a single item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'AX', 'Twenty', '20 each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'AY', 'Assembly', 'A collection of parts assembled to form a complete unit constituting a single item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BA', 'Bale', 'A shaped unit of compressed material bound with cord or metal ties and usually wrapped, e.g., paper and cloth rags.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BB', 'Bobbin', 'A cylindrical shaped reel or spool containing thread, yarn, wire.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BC', 'Block', 'A piece of material such as wood, stone or metal usually with one or more planed faces.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BF', 'Board Foot', 'A unit of measure for lumber equal to the volume of a board 12" X 12" X 1" (144 cubic inches, or 2.360 cubic decimeters).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BG', 'Bag', 'A flexible container of various sizes and shapes fabricated from materials as paper, plastic or textiles.  Includes "sack" and "pouch".', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BK', 'Book', 'A booklike package, as labels or tickets, fastened together along one edge, usally between protective covers.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BL', 'Barrel/Drum/Keg', 'A cylindrical container, metal or wood, usually with sides that bulge outward and flat ends or heads of equal diameter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BO', 'Bolt', 'A flat fold of fabric having a stiff paper board core.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BR', 'Bar', 'A solid piece or block of material having its length greater than its other dimensions, e.g., solder.  Not applicable to items as soap, beeswax, buffing compound.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BU', 'Bushel', 'A unit of dry measure equal to eight (8) gallons.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'BX', 'Box', 'A rigid three dimensional container of varying size and material.  Includes "tray" and "crate".', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CA', 'Can/Pail/Tin', 'A rigid receptacle made of fiber, metal, plastic.  May be cylindrical or any numbwe of shapes. Includes "cannister".', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CB', 'Carboy', 'A large, heavy duty, bottle-type container used for transportation and storage of liquids.  Usually encased in a rigid protective outer container for shipment.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CC', 'Cubic Centimeter', 'A metric unit of cubic measure equal to 0.000001 cubic meter, 1.0 milliliter or 0.061 cubic inch.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CF', 'Cubic Foot', 'A unit of cubic measure equal to 0.037 cubic yard or 0.028 cubic meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CG', 'Centigram', 'A unit of metric weight equal to 0.01 gram or 0.000035 ounce.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CI', 'Cubic Inch', 'A unit of cubic measure equal to 0.00058 cubic feet or 16.387 cubic centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CK', 'Cake', 'A block of compacted or congealed matter. Applicable to such items as soap, buffing compound.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CL', 'Cylinder', 'A rigid, cylindrical, metal container designed for transportation and storage of compressed gasses.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CM', 'Centimeters', 'A unit of metric length equal to 0.01 meter or 0.39 inch.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CN', 'Carton', 'A container, usually of fibreboard or pasteboard, with fixed or collapsible joints and self-locking or tuck-in flaps.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CO', 'Container', 'A general term for a receptacle or covering for shipment of goods.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CP', 'Capsule', 'A compact metallic or plastic container for liquids or solids.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CR', 'Card', 'A flat piece of thick paper or pasteboard to which various items can be attached or displayed.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CS', 'Case', 'A container designed to hold one or more specific items in a fixed position by virtue of conforming dimensions or attachments.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CT', 'Hundred Feet', 'A unit of linear measurement equal to 33.333 yards or 30.48 meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CW', 'Hundred Pounds', 'A unit of avoirdupois weight equal to 45.359 kilograms.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CY', 'Cubic Yard', 'Unit of cubic measure equal to 27 cubic feet or 0.765 cubic meter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'DC', 'Cubic Decimeter', 'A metric unit of cubic measure equal to 1.0 liter or 61.02 cubic inches.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'DL', 'Deciliter', 'A unit of metric capacity equal to 0.1 liter, 100 cubic centimeters or 6.1 cubic inches.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'DM', 'Decimeter', 'A unit of metric length equal to 0.1 meter or 3.94 inches.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'DR', 'Dram', 'A unit of avoirdupois weight equal to 1/16 (.0625) ounce or 1.771 grams.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'DZ', 'Dozen', 'Twelve each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'FM', 'Fathom', 'A unit of length equal to 6.0 feet or 1.829 meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'FO', 'Fluidounce (U.S.)', 'A liquid unit of measure equal to 1/16 (.0625) pint (U.S.), 29.573 milliliters or 29.573 cubic centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'FT', 'Foot/Foot Run', 'A unit of linear measurement equal to 12 inches or (Linear Foot)  30.480 centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'FY', 'Fifty', 'Fifty (50) each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'FZ', 'Fluidounce (Imperial)', 'A liquid unit of measure equal to 1/20 (.05) pint (Imperial), 28.416 cubic centimeters or 28.416 milliliters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GC', 'Gill (Imperial)', 'A unit of liquid or dry measure equal to 5 fluidounces, 8.669 cubic inches or 142.066 cubic centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GI', 'Gallon (Imperial)', 'A unit of liquid or dry measure equal to 277.420 cubic inches, 4.545 liters or 1.201 gallons (U.S.).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GL', 'Gallon (U.S.)', 'A unit of liquid or dry measure equal to 231 cubic inches, 3.785 liters or 0.833 gallon (Imperial).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GM', 'Gram', 'A small unit of metric mass and weight equal to 0.000001 metric ton or 0.0353 ounce.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GN', 'Grain', 'A small unit of weight equal to 1/480 (.002083) troy ounce, or 0.0648 gram.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GP', 'Group', 'A collection of related items issued as a single unit of supply, e.g., test set group.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'GR', 'Gross', '144 each of a unit of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HC', 'Hundred Cubic Meters', 'A unit of metric volume equal to 131.0 cubic yards.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HG', 'Hectogram', 'A unit of metric mass and weight equal to 100 grams or 3.527 ounces.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HK', 'Hundred Kilogram (Quintal)', 'A unit of metric mass and weight equal to 0.1 metric ton or 220.46 pounds.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HL', 'Hundred Liters  (Hectoliter)', 'A unit of metric capacity equal to 3.53 cubic feet.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HM', 'Hundred Meters  (Hectometer)', 'A unit of metric length equal to 109.36 yards or 0.062 mile.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HP', 'Half Pint (U.S.)', 'A unit of liquid measure equal to 14.4375 cubic inches or 0.2365 milliliter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HS', 'Hundred Square Feet', 'A unit of area measurement equal to 11.1 square yards or 9.3 square meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HU', 'Hundred', '100 each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HW', 'Hundred Weight', 'A unit of avoirdupois weight equal to 100 pounds or 45.359 kilograms (short hundred weight); or 112 pounds or 50.802 kilograms (long hundred weight).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'HY', 'Hundred Yards', 'A unit of linear measurement equal to 91.4 meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'IN', 'Inch ', 'A unit of linear measurement equal to 2.540 centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'IU', 'Unit', 'A standard or basic quantity into which an item of supply is dispensed or distributed.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'JR', 'Jar/Bottle', 'A rigid container having a wide mouth and often no neck, typically made of earthen ware or glass.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'KG', 'Kilogram', 'A metric unit of weight equal to 1000 grams or 2.2046 pounds.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'KM', 'Kilometer', 'A metric unit of length equal to 1000 meters or 0.62 mile.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'KP', 'Cop', 'A cylindrical or conical mass of thread, yarn, cable wound on a quill or tube.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'KT', 'Kit', 'WIP - KITS - DO NOT USE - A collection of related items issued as a single unit of supply, such as tools, instruments, repair parts, instruction sheets and often supplies typically carried in a box or bag.  Also includes selected collections of equipment components, tools and/or materials for the repair, overhaul or modification of equipment.', 2, null, null, 1, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'LB', 'Pound', 'A unit a avoirdupois weight equal to 16 ounces or 0.453 kilogram.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'LG', 'Length', 'A unit of fixed or specific linear measurement.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'LI', 'Liter', 'A unit of metric capacity equal to 1.0 cubic decimeter, 61.02 cubic inches, 1.06 quarts (U.S.) or 0.88 quart (Imperial).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'LM', 'Linear Meter', 'A term used for measuring preformed piping, insulation.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'LT', 'Lot', 'A number of units of an item of supply offered as a single item.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MC', 'Cubic Meter', 'A metric unit of cubic measure equal to 1.0 kiloliter or 1.31 cubic yards.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ME', 'Meter', 'A metric unit of linear measurement equal to 39.37 inches.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MF', 'Thousand Board Feet', 'A unit of measure for lumber equal to the volume of 1000 board foot units (12" X 12" X 1").', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MG', 'Milligram', 'A metric unit of mass and weight equal to .001 gram.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ML', 'Milliliter', 'A metric unit of capacity equal to .001 liter, 0.061 cubic inch or 1 cubic centimeter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MM', 'Millimeter', 'A metric unit of length equal to .001 meter or 0.04 inch.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MN', 'Square Millimeter', 'A metric unit of area measurement equal to 0.000001 square meter or 0.0016 square inch.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MT', 'Thousand Feet', 'A unit of linear measurement equal to 333.33 yards or 304.8 meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'MX', 'Thousand Cubic Feet', 'A unit of volume equal to 37.04 cubic yards or 765 cubic meters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'OT', 'Outfit', 'A collection of related items issued as a single item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'OZ', 'Ounce', 'A unit a avoirdupois weight equal to 1/16 (.0625) pound or 28.349 grams.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PB', 'Pint (Imperial)', 'A measure of liquid capacity equal to 1/8 (.125) gallon (Imperial), 34.678 cubic inches, 0.568 liter or 1.201 pints (U.S.).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PC', 'Piece', 'A portion or quantity of an item, often a specific length.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PD', 'Pad', 'Multiple sheets of paper that are stacked together and fastened at one end by sealing.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PE', 'Peck', 'A unit of dry measure equal to 2 gallons.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PK', 'Bundle/Pack/Package', 'A quantity of an item tied together without compression.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PM', 'Plate', 'A flat piece of square or rectangular shaped metal of uniform thickness usually 1/4 inch or more.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PR', 'Pair', 'Two like, corresponding items as gloves, shoes, bearings; or single items fabricated of two corresponding parts as shears, goggles, trousers.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PT', 'Pint (U.S.)', 'A measure of liquid capacity equal to 1/8 (.125) gallon (U.S.), 28.875 cubic inches, 0.473 liter or 0.833 pint (Imperial).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'PZ', 'Packet', 'A container used for subsistence items.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'QI', 'Quart (Imperial)', 'A unit of liquid capacity equal to 1/4 (.25) gallon (Imperial), 69.355 cubic inches, 1.136 liters or 1.201 quart (U.S.).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'QK', 'Quarter Kilogram', 'A unit of metric weight equal to 250 grams.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'QR', 'Quire', 'A measure of 24 sheets of paper.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'QT', 'Quart (U.S.)', 'A unit of liquid capacity equal to 1/4 (.25) gallon (U.S.), 57.75 cubic inches, 0.946 liter or 0.833 quart (Imperial).', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'RA', 'Ration', 'Amount of food or supplies allotted to an individual, usually for one day.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'RL', 'Roll/Spool/Coil/Cone', 'A cylindrical configuration of flexible material which has been rolled on itself as textiles, tape, paper, film and may utilize a core with or without flanges.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'RM', 'Ream', 'A quantity of paper varying from 480 to 516 sheets, depending upon grade.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SC', 'Square Centimeter', 'A metric unit of area measurement equal to 0.0001 square meter or 0.155 square inch.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SD', 'Square Decimeter', 'A metric unit of area measurement equal to 0.01 square meter or 15.5 square inches.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SF', 'Square Foot/Super Foot', 'A unit of area measurement equal to 144 square inches or 0.093 square meter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SH', 'Sheet', 'A flat piece of rectangular shaped material of uniform thickness that is very thin in relation to its length and width, such as paper, metal and plywood.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SI', 'Square Inch', 'A unit of area measurement equal to 0.00694 square feet or 6.4516 square centimeters.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SK', 'Stick', 'Material in a relatively long, slendor and often cylindrical form for ease of application, e.g., abrasives.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SM', 'Square Meter', 'A metric unit of area measurement equal to 10.76 square feet.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SN', 'Skein', 'A loop of yarn, 120 yards in length, usually wound on a circular core.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SO', 'Shot', 'A unit of linear measure equal to 15 fathoms or 90 feet, usually applied to anchor chain.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SP', 'Strip', 'A relatively narrow, flat length of material, uniform in width, such as paper, wood and metal.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ST', 'Set', 'A collection of matched or related items issued as a single item of supply,  i.e., tool set, matched set.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'SY', 'Square Yard', 'A unit of area measurement equal to 1296 square inches, 9 square feet or 0.836 square meter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TE', 'Ten', '10 each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TH', 'Thousand', '1000 each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TK', 'Ton, Metric (Thousand Kilograms)', 'A metric unit of weight equal to 2204.6 pounds.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TL', 'Thousand Liter (Kiloliter)', 'A metric unit of capacity equal to 1 cubic meter or 1.31 cubic yards.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TN', 'Ton, Short', 'A unit of avoirdupois weight equal to 2000 pounds or 0.907 metric ton.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TO', 'Troy Ounce', 'A unit of troy weight, usually applied to precious metals, equal to 1/12 (.0833) troy pound or 0.373 kilogram.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TT', 'Tablet', 'A compressed or molded block of solid material; a collection of sheet paper glued together at one edge.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TU', 'Tube', 'A squeeze-type container used in packaging commodities as adhesives,toothpaste, pharmaceuticals.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'TX', 'Ton, Long', 'A unit of avoirdupois weight equal to 2240 pounds or 1.016 metric tons.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'VC', 'Five Hundred', 'Five hundred (500) each of an item of supply.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'VI', 'Vial', ' A small glass container, tubular in shape (generally less than one inch in diameter) having a flat bottom and variety of neck shapes.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'YD', 'Yard', 'A unit of length equal to 3 feet or 0.914 meter.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
insert into REF_QTY_UNIT (QTY_UNIT_DB_ID, QTY_UNIT_CD, DESC_SDESC, DESC_LDESC, DECIMAL_PLACES_QT, BITMAP_DB_ID, BITMAP_TAG, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ZV', 'Syphon', 'An aerated container from which liquid is forced by gas pressure.', 2, null, null, 0, to_date('05-10-2007', 'dd-mm-yyyy'), to_date('05-10-2007', 'dd-mm-yyyy'), 0, 'MXI');
