/********************************************
** INSERT SCRIPT FOR TABLE "REF_REQ_ACTION"
** 10-Level
** DATE: June 22th, 2009
*********************************************/

INSERT INTO REF_REQ_ACTION ( REQ_ACTION_DB_ID, REQ_ACTION_CD, USER_CD, DESC_SDESC, DESC_LDESC, GENERATE_REQ_BOOL, DEFAULT_BOOL, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'BENCH', 'BENCH', 'BENCHSTOCK', 'Retrieve parts from benchstock.  No request is generated.', 0, 0, 0, '17-JUN-09', '17-JUN-09', 0, 'MXI');

INSERT INTO REF_REQ_ACTION ( REQ_ACTION_DB_ID, REQ_ACTION_CD, USER_CD, DESC_SDESC, DESC_LDESC, GENERATE_REQ_BOOL, DEFAULT_BOOL, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'ASREQ', 'ASREQ', 'AS REQUIRED', 'As Required.  By Default, no request is generated.', 0, 0, 0, '17-JUN-09', '17-JUN-09', 0, 'MXI');
