/********************************************
** INSERT SCRIPT FOR TABLE "REF_PURCH_TYPE"
** 10-Level
** DATE: 16-JUN-2006
*********************************************/
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ACFT', 'Aircraft', null, 0, '16-JUN-06', '16-JUN-06', 0, 'MXI');
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'ENG', 'Engine', null, 0, '16-JUN-06', '16-JUN-06', 0, 'MXI');
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CONSUM', 'Consumable', null, 0, '16-JUN-06', '16-JUN-06', 0, 'MXI');
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'OFFICE', 'Office Supplies', null, 0, '16-JUN-06', '16-JUN-06', 0, 'MXI');
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'CMNHW', 'Common Hardware', null, 0, '13-JUL-06', '13-JUL-06', 0, 'MXI');
insert into REF_PURCH_TYPE (PURCH_TYPE_DB_ID, PURCH_TYPE_CD, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (10, 'OTHER', 'Other', null, 0, '13-JUL-06', '13-JUL-06', 0, 'MXI');


