/********************************************
** INSERT SCRIPT FOR TABLE "REF_CURRENCY"
** 10-Level
** DATE: 31-MAY-2005 TIME: 00:00:00
*********************************************/
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'USD', 0, 01, 'US Dollars', NULL, 1, 1, 1, 0,'22-OCT-04', '22-OCT-04', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'CAD', 0, 01, 'Canadian Dollars', NULL, 0, 0.9811913496, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'EURO', 0, 01, 'Euros', NULL, 0, 0.809567, 1, 0,'22-OCT-04', '22-OCT-04', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'GBR', 0, 01, 'United Kingdom Pounds', NULL, 0, 0.54796, 1, 0,'22-OCT-04', '22-OCT-04', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'AUD', 0, 01, 'Australian Dollars', NULL, 0, 1.1143184175, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'BEF', 0, 01, 'Belgian Franc', NULL, 0, 28.5378692927, 10, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'CHF', 0, 01, 'Swiss Frank', NULL, 0, 1.1770197382, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'DEM', 0, 01, 'German Mark', NULL, 0, 1.3836231845, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'DKK', 0, 01, 'Danish Krone', NULL, 0, 5.2703971438, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'ECU', 0, 01, 'European Currency Unit', NULL, 0, 1, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'ESP', 0, 01, 'Spanish Peseta', NULL, 0, 117.7073299671, 100, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'EUR', 0, 01, 'Euros', NULL, 0, 0.7072486935, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'FIM', 0, 01, 'Finnish Markka', NULL, 0, 4.2062192913, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'FRF', 0, 01, 'French Franc', NULL, 0, 0.4898156832, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'GBP', 0, 01, 'United Kingdom Pounds', NULL, 0, 0.48975, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'GRD', 0, 01, 'Greek Drachma', NULL, 0, 241.0585787644, 100, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'HKD', 0, 01, 'Hong Kong Dollar', NULL, 0, 7.7564910807, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'ITL', 0, 01, 'Italian Lira', NULL, 0, 1369.7857499757, 1000, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'JPY', 0, 01, 'Japanese Yen', NULL, 0, 116.9169677402, 100, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'NLG', 0, 01, 'Netherlands Guilder', NULL, 0, 1.5589822468, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'NOK', 0, 01, 'Norwegian Krone', NULL, 0, 5.4093416374, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'NZD', 0, 01, 'New Zealand Dollar', NULL, 0, 1.3139667409, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'PTE', 0, 01, 'Portuguese Escudo', NULL, 0, 141.8280439849, 100, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'SEK', 0, 01, 'Swedish Krona', NULL, 0, 6.4645375828, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'SGD', 0, 01, 'Singapore Dollar', NULL, 0, 1.4715648256, 1, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
insert into REF_CURRENCY ( CURRENCY_DB_ID, CURRENCY_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, DEFAULT_BOOL, EXCHG_QT, SPEC2K_MULT_QT, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 10, 'TRL', 0, 01, 'Turkish Lira', NULL, 0, 1178947.9935001987, 100, 0,'05-OCT-07', '05-OCT-07', 100, 'MXI');
