/********************************************
** INSERT SCRIPT FOR TABLE "REF_SIZE_CLASS"
** 10-Level
** DATE: 03-MARCH-2005 TIME: 00:00:00
*********************************************/
INSERT INTO REF_SIZE_CLASS ( SIZE_CLASS_DB_ID, SIZE_CLASS_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'SMALL', 0,1 ,'SMALL', 'SMALL', 0, '19-APR-05', '19-APR-05', 0, 'MXI');
INSERT INTO REF_SIZE_CLASS ( SIZE_CLASS_DB_ID, SIZE_CLASS_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'MEDIUM',0,1 ,'MEDIUM', 'MEDIUM', 0, '19-APR-05', '19-APR-05', 0, 'MXI');
INSERT INTO REF_SIZE_CLASS ( SIZE_CLASS_DB_ID, SIZE_CLASS_CD, BITMAP_DB_ID, BITMAP_TAG, DESC_SDESC, DESC_LDESC, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
VALUES (10, 'LARGE', 0,1 ,'LARGE', 'LARGE', 0, '19-APR-05', '19-APR-05', 0, 'MXI');