--liquibase formatted sql

--changeset OPER-29338-3:1 stripComments:false
INSERT INTO ref_usg_snapshot_src_type ( source_db_id, source_cd, source_sdesc, source_ldesc, rstat_cd, revision_no, ctrl_db_id, creation_db_id, creation_dt, revision_dt, revision_db_id, revision_user)
SELECT 0, 'MAINTENIX', 'Auto generated data', 'Data generated by Maintenix through OOS processes', 0, 1, 0, 0, sysdate, sysdate, 0, user
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ref_usg_snapshot_src_type WHERE source_db_id = 0 AND source_cd = 'MAINTENIX' );

--changeset OPER-29338-3:2 stripComments:false
INSERT INTO ref_usg_snapshot_src_type ( source_db_id, source_cd, source_sdesc, source_ldesc, rstat_cd, revision_no, ctrl_db_id, creation_db_id, creation_dt, revision_dt, revision_db_id, revision_user)
SELECT 0, 'CUSTOMER', 'Data inputed by a user', 'Data specified by the user that will only be entered in manually and not touched by OOS', 0, 1, 0, 0, sysdate, sysdate, 0, user
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ref_usg_snapshot_src_type WHERE source_db_id = 0 AND source_cd = 'CUSTOMER' );

--changeset OPER-29338-3:3 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
--preconditions onFail:MARK_RAN
BEGIN
   UPG_PARALLEL_V1_PKG.PARALLEL_UPDATE_BEGIN('EVT_INV_USAGE');
   UPDATE
      evt_inv_usage
   SET
      evt_inv_usage.source_db_id = 0, 
      evt_inv_usage.source_cd = 'MAINTENIX'
	WHERE
      evt_inv_usage.source_db_id IS NULL OR
      evt_inv_usage.source_cd IS NULL;
  UPG_PARALLEL_V1_PKG.PARALLEL_UPDATE_END('EVT_INV_USAGE', FALSE);
END;
/

--changeSet OPER-29338-3:4 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
    utl_migr_schema_pkg.table_column_modify ('
        ALTER TABLE EVT_INV_USAGE MODIFY source_db_id NOT NULL
    ');
END;
/

--changeSet OPER-29338-3:5 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
    utl_migr_schema_pkg.table_column_modify ('
        ALTER TABLE EVT_INV_USAGE MODIFY source_cd NOT NULL
    ');
END;
/