--liquibase formatted sql
--changeSet OPER-18840:1 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
CREATE OR REPLACE TRIGGER "TTRK_UTL_USER_ROLE_CACHE"
   FOR INSERT OR UPDATE OR DELETE ON "UTL_USER_ROLE"
   
COMPOUND TRIGGER
   AFTER STATEMENT IS
   BEGIN
      -- Update  CacheFactory.MENU_NODE_NAME cache timestamp
      UTL_CACHE_PKG.UPDATE_CACHE_TREE_ROOT_NODE('Menu');
   END AFTER STATEMENT;
END "TTRK_UTL_USER_ROLE_CACHE";
/

--changeSet OPER-18840:2 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
CREATE OR REPLACE TRIGGER "TTRK_UTL_MENU_GROUP_CACHE"
   FOR INSERT OR UPDATE OR DELETE ON "UTL_MENU_GROUP"
   
COMPOUND TRIGGER
   AFTER STATEMENT IS
   BEGIN
      -- Update  CacheFactory.MENU_NODE_NAME cache timestamp
      UTL_CACHE_PKG.UPDATE_CACHE_TREE_ROOT_NODE('Menu');
   END AFTER STATEMENT;
END "TTRK_UTL_MENU_GROUP_CACHE";
/

--changeSet OPER-18840:3 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
CREATE OR REPLACE TRIGGER "TTRK_UTL_MENU_GROUP_ITEM_CACHE"
   FOR INSERT OR UPDATE OR DELETE ON "UTL_MENU_GROUP_ITEM"
   
COMPOUND TRIGGER
   AFTER STATEMENT IS
   BEGIN
      -- Update  CacheFactory.MENU_NODE_NAME cache timestamp
      UTL_CACHE_PKG.UPDATE_CACHE_TREE_ROOT_NODE('Menu');
   END AFTER STATEMENT;
END "TTRK_UTL_MENU_GROUP_ITEM_CACHE";
/

--changeSet OPER-18840:4 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
CREATE OR REPLACE TRIGGER "TTRK_UTL_MENU_ITEM_ARG_CACHE"
   FOR INSERT OR UPDATE OR DELETE ON "UTL_MENU_ITEM_ARG"
   
COMPOUND TRIGGER
   AFTER STATEMENT IS
   BEGIN
      -- Update  CacheFactory.MENU_NODE_NAME cache timestamp
      UTL_CACHE_PKG.UPDATE_CACHE_TREE_ROOT_NODE('Menu');
   END AFTER STATEMENT;
END "TTRK_UTL_MENU_ITEM_ARG_CACHE";
/

--changeSet OPER-18840:5 stripComments:false endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
CREATE OR REPLACE TRIGGER "TTRK_UTL_MENU_ARG_CACHE"
   FOR INSERT OR UPDATE OR DELETE ON "UTL_MENU_ARG"
   
COMPOUND TRIGGER
   AFTER STATEMENT IS
   BEGIN
      -- Update  CacheFactory.MENU_NODE_NAME cache timestamp
      UTL_CACHE_PKG.UPDATE_CACHE_TREE_ROOT_NODE('Menu');
   END AFTER STATEMENT;
END "TTRK_UTL_MENU_ARG_CACHE";
/