--liquibase formatted sql


--changeSet MTX-563:1 stripComments:false
-- ARC UI
INSERT  INTO 
	UTL_MENU_ITEM (MENU_ID,TODO_LIST_ID,MENU_NAME,MENU_LINK_URL,NEW_WINDOW_BOOL,MENU_LDESC,REPL_APPROVED,UTL_ID)
SELECT 120940,NULL,'web.menuitem.ARC_MESSAGE_MANAGEMENT', '/arc',0,'Manage ARC Messages',0,0
  FROM DUAL
 WHERE NOT EXISTS ( SELECT 1 FROM UTL_MENU_ITEM WHERE MENU_ID = 120940 );