-- add 4 users
INSERT INTO UTL_USER (USER_ID, UTL_ID, USERNAME, FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL_ADDR, ALERT_EMAIL_ADDR) VALUES (999000,0,'user1','first1','last1','mid1','email1','alert1');
INSERT INTO UTL_USER (USER_ID, UTL_ID, USERNAME, FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL_ADDR, ALERT_EMAIL_ADDR) VALUES (999001,0,'user2','first2','last2','mid2','email2','alert2');
INSERT INTO UTL_USER (USER_ID, UTL_ID, USERNAME, FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL_ADDR, ALERT_EMAIL_ADDR) VALUES (999002,0,'user3','first3','last3','mid3','email3','alert3');
INSERT INTO UTL_USER (USER_ID, UTL_ID, USERNAME, FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL_ADDR, ALERT_EMAIL_ADDR) VALUES (999003,0,'userNoOrg','firstNoOrg','lastNoOrg','midNoOrg','emailNoOrg','alertNoOrg');

-- add HR entries for the first 3 users
INSERT INTO ORG_HR (HR_ID, HR_DB_ID,HR_CD,USER_ID) VALUES (998000,0,'org1',999000);
INSERT INTO ORG_HR (HR_ID, HR_DB_ID,HR_CD,USER_ID) VALUES (998001,0,'org1',999001);
INSERT INTO ORG_HR (HR_ID, HR_DB_ID,HR_CD,USER_ID) VALUES (998002,0,'org2',999002);

-- add orgs
INSERT INTO ORG_ORG (ORG_ID,ORG_DB_ID,ORG_SDESC,ORG_CD,COMPANY_ORG_ID,COMPANY_ORG_DB_ID,ORG_TYPE_DB_ID,ORG_TYPE_CD) VALUES (997000,0,'desc1','code1',997000,0,0,'CREW');
INSERT INTO ORG_ORG (ORG_ID,ORG_DB_ID,ORG_SDESC,ORG_CD,COMPANY_ORG_ID,COMPANY_ORG_DB_ID,ORG_TYPE_DB_ID,ORG_TYPE_CD) VALUES (997001,0,'desc2','code2',997000,0,0,'MRO');

-- add org_hr/org association table entries
INSERT INTO ORG_ORG_HR (HR_ID, HR_DB_ID,ORG_ID,ORG_DB_ID,DEFAULT_ORG_BOOL) VALUES (998000,0,997000,0,1);
INSERT INTO ORG_ORG_HR (HR_ID, HR_DB_ID,ORG_ID,ORG_DB_ID,DEFAULT_ORG_BOOL) VALUES (998001,0,997000,0,1);
INSERT INTO ORG_ORG_HR (HR_ID, HR_DB_ID,ORG_ID,ORG_DB_ID,DEFAULT_ORG_BOOL) VALUES (998002,0,997001,0,1);