Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4318,'F-2000',0,'ACFT',null,null,0,73,null,null,null,null,null,'Falcon 2000',null,null,0,to_date('03-DEC-99','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4329,'738-1',0,'ENG',null,null,0,17,null,null,null,null,null,'CFE738-1',null,null,0,to_date('02-DEC-99','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4330,'36-150',0,'APU',null,null,0,11,null,null,null,null,null,'AlliedSignal APU',null,null,0,to_date('02-DEC-99','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'101',0,'ENG',null,null,0,69,null,null,null,null,null,'Model Engine',null,null,0,to_date('22-AUG-08','DD-MON-RR'),to_date('22-AUG-08','DD-MON-RR'),4650,'ysotozaki');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'APP-CD',0,'MODULE',null,null,0,19,null,null,null,null,null,'Applicability Code Test',null,null,0,to_date('29-SEP-05','DD-MON-RR'),to_date('29-SEP-05','DD-MON-RR'),4650,'lsoh');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'C17',0,'ACFT',null,null,0,26,null,null,null,null,null,'Globemaster III',null,null,0,to_date('22-AUG-08','DD-MON-RR'),to_date('22-AUG-08','DD-MON-RR'),4650,'ysotozaki');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'CONSUM',0,'COMHW',null,null,0,26,null,null,null,null,null,'Consumable assembly',null,null,0,to_date('30-AUG-03','DD-MON-RR'),to_date('30-AUG-03','DD-MON-RR'),4650,'TABASCO_COREM2');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'GENERIC',0,'ACFT',null,null,0,26,null,null,null,null,null,'Generic Aircraft',null,null,0,to_date('02-AUG-01','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TEST',10,'MODULE',null,null,0,26,null,null,null,null,null,'Assembly for Core unit testing',null,null,0,to_date('26-FEB-04','DD-MON-RR'),to_date('26-FEB-04','DD-MON-RR'),4650,'TABASCO_COREM10');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TSE',0,'TSE',null,null,0,131,null,null,null,null,null,'Tools & Service Equipment',null,null,0,to_date('16-JAN-06','DD-MON-RR'),to_date('16-JAN-06','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TestAsm',10,'MODULE',null,null,0,26,null,null,null,null,null,'Assembly with Config Slot for testing',null,null,0,to_date('25-MAY-07','DD-MON-RR'),to_date('25-MAY-07','DD-MON-RR'),4650,'MX0706_MASTER');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5001,'CFM56',0,'ENG',null,null,0,17,null,null,null,null,null,'CFM56-3C',null,null,0,to_date('11-FEB-02','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'A320',0,'ACFT',null,null,0,26,null,null,null,null,null,'Airbus A319/A320','Airbus A320 aircraft.','30-SEP-99',0,to_date('04-OCT-01','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (8000000,'B767-200',0,'ACFT',null,null,0,26,null,null,null,null,null,'Boeing 767-200',null,null,0,to_date('12-APR-01','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (8000001,'CF6-80',0,'ENG',null,null,0,17,null,null,null,null,null,'General Electric CF6-80',null,null,0,to_date('06-APR-01','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (8000002,'APU G20',0,'APU',null,null,0,11,null,null,null,null,null,'G20 757/767 APU',null,null,0,to_date('06-APR-01','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');
