Insert into CAPACITY_PATTERN(CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_PATTERN_CD,CAPACITY_PATTERN_NAME,CAPACITY_PATTERN_TYPE_DB_ID,CAPACITY_PATTERN_TYPE_CD,CAPACITY_PATTERN_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,'CP001','Winter Pattern',0,'WEEKLY','7 day pattern',0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into CAPACITY_PATTERN(CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_PATTERN_CD,CAPACITY_PATTERN_NAME,CAPACITY_PATTERN_TYPE_DB_ID,CAPACITY_PATTERN_TYPE_CD,CAPACITY_PATTERN_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,2,'CP002','Summer Pattern',0,'DAILY','daily pattern',0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC_CAP_STD(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_STD_ID,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,4650,100013,4650,1,1,to_date('19-JAN-10','DD-MON-RR'),to_date('21-JAN-10','DD-MON-RR'),0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC_CAP_STD(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_STD_ID,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,4650,100013,4650,1,2,to_date('19-JAN-10','DD-MON-RR'),to_date('21-JAN-10','DD-MON-RR'),0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');
