Insert into CAPACITY_PATTERN(CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_PATTERN_CD,CAPACITY_PATTERN_NAME,CAPACITY_PATTERN_TYPE_DB_ID,CAPACITY_PATTERN_TYPE_CD,CAPACITY_PATTERN_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,'CP001','Winter Pattern',0,'WEEKLY','7 day pattern',0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into CAPACITY_PATTERN(CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,CAPACITY_PATTERN_CD,CAPACITY_PATTERN_NAME,CAPACITY_PATTERN_TYPE_DB_ID,CAPACITY_PATTERN_TYPE_CD,CAPACITY_PATTERN_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,2,'CP002','Summer Pattern',0,'DAILY','daily pattern',0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,DEFAULT_CAPACITY,LABOR_RATE,AH_EVT_CTRL_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,4650,100013,0,0.00000,0,0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,DEFAULT_CAPACITY,LABOR_RATE,AH_EVT_CTRL_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,6,4650,1212,0,0.00000,0,0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC_CAPACITY(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1,4650,100013,4650,1,0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into LRP_LOC_CAPACITY(LRP_DB_ID,LRP_ID,LOC_DB_ID,LOC_ID,CAPACITY_PATTERN_DB_ID,CAPACITY_PATTERN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,6,4650,1212,4650,1,0,to_date('19-JAN-10','DD-MON-RR'),to_date('19-JAN-10','DD-MON-RR'),4650,'MXMATRIX_DEV');
