--liquibase formatted sql


--changeSet OPER-8688:1 stripComments:false
INSERT INTO
   UTL_CONFIG_PARM
   (
      PARM_VALUE, PARM_NAME, PARM_TYPE, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID
   )
   SELECT '5', 'START_FLIGHT_BUFFER', 'PLANNING_VIEWER','Planning viewer parameters','USER', 'NUMBER', '5', 0, 'Planning Viewer', '8.0', 0
   FROM
      dual
   WHERE
      NOT EXISTS ( SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'START_FLIGHT_BUFFER' );

--changeSet OPER-8688:2 stripComments:false
INSERT INTO
   UTL_CONFIG_PARM
   (
      PARM_VALUE, PARM_NAME, PARM_TYPE, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID
   )
   SELECT '5', 'END_FLIGHT_BUFFER', 'PLANNING_VIEWER','Planning viewer parameters','USER', 'NUMBER', '5', 0, 'Planning Viewer', '8.0', 0
   FROM
      dual
   WHERE
      NOT EXISTS ( SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'END_FLIGHT_BUFFER' );

--changeSet OPER-8688:3 stripComments:false
INSERT INTO
   UTL_CONFIG_PARM
   (
      PARM_VALUE, PARM_NAME, PARM_TYPE, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID
   )
   SELECT '60', 'MAX_START_FLIGHT_BUFFER', 'PLANNING_VIEWER','The maximum buffer in minutes between a flight and a work package.','GLOBAL', 'NUMBER', '60', 0, 'Planning Viewer', '8.0', 0
   FROM
      dual
   WHERE
      NOT EXISTS ( SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_START_FLIGHT_BUFFER' );

--changeSet OPER-8688:4 stripComments:false
INSERT INTO
   UTL_CONFIG_PARM
   (
      PARM_VALUE, PARM_NAME, PARM_TYPE, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID
   )
   SELECT '60', 'MAX_END_FLIGHT_BUFFER', 'PLANNING_VIEWER','The maximum buffer in minutes between a flight and a work package.','GLOBAL', 'NUMBER', '60', 0, 'Planning Viewer', '8.0', 0
   FROM
      dual
   WHERE
      NOT EXISTS ( SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_END_FLIGHT_BUFFER' );