--liquibase formatted sql

--changeSet OPER-8830:1 stripComments:false
INSERT INTO
   UTL_CONFIG_PARM
   (
      PARM_VALUE, PARM_NAME, PARM_TYPE, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID
   )
   SELECT '', 'AIRCRAFT_GROUP', 'PLANNING_VIEWER','Planning viewer parameters','USER', 'STRING', '', 0, 'Planning Viewer', '8.0', 0
   FROM
      dual
   WHERE
      NOT EXISTS ( SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'AIRCRAFT_GROUP' );