--liquibase formatted sql

--changeSet 0ref_usg_snapshot_src_type:1 stripComments:false
/******************************************************
** INSERT SCRIPT FOR TABLE "REF_USG_SNAPSHOT_SRC_TYPE"
** 0-Level
** DATE: 19-FEB-2019
*******************************************************/
INSERT INTO ref_usg_snapshot_src_type ( source_db_id, source_cd, source_sdesc, source_ldesc, rstat_cd, revision_no, ctrl_db_id, creation_db_id, creation_dt, revision_dt, revision_db_id, revision_user)
VALUES (0, 'MAINTENIX', 'Auto generated data', 'Data generated by Maintenix through OOS processes', 0, 1, 0, 0, sysdate, sysdate, 0, user);

--changeSet 0ref_usg_snapshot_src_type:2 stripComments:false
INSERT INTO ref_usg_snapshot_src_type ( source_db_id, source_cd, source_sdesc, source_ldesc, rstat_cd, revision_no, ctrl_db_id, creation_db_id, creation_dt, revision_dt, revision_db_id, revision_user)
VALUES (0, 'CUSTOMER', 'Data inputed by a user', 'Data specified by the user that will only be entered in manually and not touched by OOS', 0, 1, 0, 0, sysdate, sysdate, 0, user);