/********************************************
** 10-Level INSERT SCRIPT FOR UTL_MENU_GROUP
*********************************************/
insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10001, 'Maintenance Controller', 1, 10000, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10002, 'Line Supervisor', 1, 10001, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10003, 'Heavy Technician', 1, 10002, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10004, 'Shop Controller', 1, 10004, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10005, 'Progress Monitor', 1, 10010, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10006, 'Production Controller', 1, 10006, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10007, 'Crew Lead', 1, 10007, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10009, 'Engineer', 1, 10009, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10011, 'Line Technician', 1, 10011, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10013, 'Quality Control Inspector', 1, 10013, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10014, 'Technical Records', 1, 10014, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10017, 'Storeroom Clerk', 1, 10017, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10018, 'Purchasing Agent', 1, 10018, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10019, 'Purchasing Manager', 1, 10019, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10020, 'Material Controller', 1, 10020, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10021, 'Repair Router', 1, 10021, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10022, 'Storeroom Supervisor', 1, 10022, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10023, 'Line Planner', 1, 10008, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10024, 'Heavy Planner', 1, 10023, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10026, 'Long Range Planner', 1, 10029, 0, 10);

insert into UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL, UTL_ID)
values (10027, 'Warranty Agent', 1, 10030, 0, 10);

-- Deployed Operations
INSERT INTO UTL_MENU_GROUP (GROUP_ID, GROUP_NAME, GROUP_ORDER, ROLE_ID, ALL_USERS_BOOL,UTL_ID)
VALUES (10050, 'Deployed Operations', 1 , 10032, 0, 10);