--liquibase formatted sql


--changeSet DEV-74:1 stripComments:false
INSERT INTO utl_config_parm(PARM_NAME, PARM_TYPE, PARM_VALUE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'ACTION_ENFORCE_WORKSCOPE_ORDER_REQ','SECURED_RESOURCE','true', 0,'Permission to toggle enforce workscope order.','USER', 'TRUE/FALSE', 'TRUE', 1, 'Maint Program - Task Definitions', '7.1.0', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'ACTION_ENFORCE_WORKSCOPE_ORDER_REQ' AND PARM_TYPE = 'SECURED_RESOURCE');

--changeSet DEV-74:2 stripComments:false
INSERT INTO utl_config_parm(PARM_NAME, PARM_TYPE, PARM_VALUE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'ACTION_TOGGLE_ENFORCE_WORKSCOPE_ORDER','SECURED_RESOURCE','true', 0,'Permission to enable/disable enforce workscope order.','USER', 'TRUE/FALSE', 'TRUE', 1, 'Maint Program - Task Definitions', '7.1.0', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'ACTION_TOGGLE_ENFORCE_WORKSCOPE_ORDER' AND PARM_TYPE = 'SECURED_RESOURCE');