--liquibase formatted sql


--changeSet MX-17269:1 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DAYS_IN_THE_PAST', 'INFO', 'LOGIC', 0, 'Severity of the validation for creation/completion of a flight further in the past than allowed.', 'USER', 'WARNING/ERROR/INFO', 'INFO', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_PAST');

--changeSet MX-17269:2 stripComments:false
UPDATE UTL_CONFIG_PARM
   SET PARM_VALUE = 'INFO',
       DEFAULT_VALUE = 'INFO'
 WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_PAST'
   AND PARM_TYPE = 'LOGIC';   

--changeSet MX-17269:3 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DAYS_IN_THE_PAST_VALUE', '3', 'LOGIC', 0, 'How many days in the past the planning and completion of a flight is allowed.', 'USER', 'Number', '3', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_PAST_VALUE');

--changeSet MX-17269:4 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DAYS_IN_THE_FUTURE', 'INFO', 'LOGIC', 0, 'Severity of the validation for creation/update of a flight further in the future than allowed.', 'USER', 'WARNING/ERROR/INFO', 'INFO', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_FUTURE');

--changeSet MX-17269:5 stripComments:false
UPDATE UTL_CONFIG_PARM
   SET PARM_VALUE = 'INFO',
       DEFAULT_VALUE = 'INFO'
 WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_FUTURE'
   AND PARM_TYPE = 'LOGIC';

--changeSet MX-17269:6 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DAYS_IN_THE_FUTURE_VALUE', '60', 'LOGIC', 0, 'How many days in the future the planning and completion of a flight is allowed.', 'USER', 'Number', '60', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DAYS_IN_THE_FUTURE_VALUE');

--changeSet MX-17269:7 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DURATION', 'INFO', 'LOGIC', 0, 'Severity of the validation for flight duration more than allowed.', 'USER', 'WARNING/ERROR/INFO', 'INFO', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DURATION');

--changeSet MX-17269:8 stripComments:false
UPDATE UTL_CONFIG_PARM
   SET PARM_VALUE = 'INFO',
       DEFAULT_VALUE = 'INFO'
 WHERE PARM_NAME = 'MAX_FLIGHT_DURATION'
   AND PARM_TYPE = 'LOGIC';   

--changeSet MX-17269:9 stripComments:false
INSERT INTO UTL_CONFIG_PARM (PARM_NAME, PARM_VALUE, PARM_TYPE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'MAX_FLIGHT_DURATION_VALUE', '', 'LOGIC', 0, 'How many hours maximum a flight can last, configurable by assembly.', 'USER', 'String of format: assmbl_bom_cd=hours,assmbl_bom_cd=hours...Hours value has to be positive whole number', '', 1, 'Ops - Flights', '7.1-SP2', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM UTL_CONFIG_PARM WHERE PARM_NAME = 'MAX_FLIGHT_DURATION_VALUE');