--liquibase formatted sql


--changeSet MX-17584:1 stripComments:false
insert into DB_TYPE_CONFIG_PARM (PARM_NAME, PARM_TYPE, DB_TYPE_CD)
SELECT 'ACTION_ADD_PART_REQUIREMENT', 'SECURED_RESOURCE','MASTER'
FROM DUAL WHERE NOT EXISTS ( SELECT 1 FROM DB_TYPE_CONFIG_PARM WHERE PARM_NAME = 'ACTION_ADD_PART_REQUIREMENT' AND PARM_TYPE = 'SECURED_RESOURCE' AND DB_TYPE_CD = 'MASTER');