--liquibase formatted sql


--changeSet MX-20730:1 stripComments:false
INSERT INTO DB_TYPE_CONFIG_PARM 
	(
		PARM_NAME, 
		PARM_TYPE, 
		DB_TYPE_CD
	)
SELECT
	'ACTION_INCLUDE_ALL_VENDOR_ORGANIZATIONS',
	'SECURED_RESOURCE',
	'MASTER'
FROM 
	dual 
WHERE NOT EXISTS 
	(
		SELECT 
			1 
		FROM 
			DB_TYPE_CONFIG_PARM 
		WHERE 
			DB_TYPE_CONFIG_PARM.parm_name = 'ACTION_INCLUDE_ALL_VENDOR_ORGANIZATIONS' AND
			DB_TYPE_CONFIG_PARM.parm_type = 'SECURED_RESOURCE' AND
			DB_TYPE_CONFIG_PARM.db_type_cd = 'MASTER'
	)
;