--liquibase formatted sql


--changeSet MX-20516:1 stripComments:false
INSERT INTO utl_config_parm(PARM_NAME, PARM_TYPE, PARM_VALUE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'ACTION_DUPLICATE_BLOCK','SECURED_RESOURCE','false', 0,'Visibility control for Duplicate Block button.','USER', 'true/false', 'false', 1, 'Maint Program - Blocks', '7.5', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM utl_config_parm WHERE PARM_NAME = 'ACTION_DUPLICATE_BLOCK' AND PARM_TYPE = 'SECURED_RESOURCE');

--changeSet MX-20516:2 stripComments:false
INSERT INTO DB_TYPE_CONFIG_PARM (PARM_NAME, PARM_TYPE, DB_TYPE_CD)
SELECT 'ACTION_DUPLICATE_BLOCK', 'SECURED_RESOURCE', 'MASTER'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DB_TYPE_CONFIG_PARM WHERE PARM_NAME = 'ACTION_DUPLICATE_BLOCK' AND PARM_TYPE = 'SECURED_RESOURCE' AND DB_TYPE_CD = 'MASTER');

--changeSet MX-20516:3 stripComments:false
INSERT INTO utl_config_parm(PARM_NAME, PARM_TYPE, PARM_VALUE, ENCRYPT_BOOL, PARM_DESC, CONFIG_TYPE, ALLOW_VALUE_DESC, DEFAULT_VALUE, MAND_CONFIG_BOOL, CATEGORY, MODIFIED_IN, UTL_ID)
SELECT 'ACTION_DUPLICATE_MASTER_PANEL_CARD','SECURED_RESOURCE','false', 0,'Visibility control for Duplicate MPC button.','USER', 'true/false', 'false', 1, 'Maint Program - Master Panel Cards', '7.5', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM utl_config_parm WHERE PARM_NAME = 'ACTION_DUPLICATE_MASTER_PANEL_CARD' AND PARM_TYPE = 'SECURED_RESOURCE');

--changeSet MX-20516:4 stripComments:false
INSERT INTO DB_TYPE_CONFIG_PARM (PARM_NAME, PARM_TYPE, DB_TYPE_CD)
SELECT 'ACTION_DUPLICATE_MASTER_PANEL_CARD', 'SECURED_RESOURCE', 'MASTER'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM DB_TYPE_CONFIG_PARM WHERE PARM_NAME = 'ACTION_DUPLICATE_MASTER_PANEL_CARD' AND PARM_TYPE = 'SECURED_RESOURCE' AND DB_TYPE_CD = 'MASTER');