--liquibase formatted sql


--changeSet QC-5463:1 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- QC-5463: 
-- QC-5464: Update lrp_plan_cofig to reference 0-level data instead of 10-level
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Author(s): Abhishek Sur 
-- Date:      Decembert 16, 2010 AD of the Gregorian Calendar
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- 1) Drop existing constraints
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_ADHOCSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:2 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_OVERFLOWSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:3 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_OVERLAPSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:4 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_DURLESSMINSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:5 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_DURGRTMAXSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:6 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_OVERDUESEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:7 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_EXTDEADSEV_LRPPLANCONFIG');
END;
/


--changeSet QC-5463:8 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_PLANBFOREMINYDSEV_LRPPLANCO');
END;
/


--changeSet QC-5463:9 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_PLANAFTMAXYDSEV_LRPPLANCONF');
END;
/


--changeSet QC-5463:10 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_OUTOFSEQSEV_LRPPLANCONF');
END;
/


--changeSet QC-5463:11 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_UPDATEACTSEV_LRPPLANCONF');
END;
/


--changeSet QC-5463:12 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_EXTRACTEXCSEV_LRPPLANCONF');
END;
/


--changeSet QC-5463:13 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_PREFFECTDTSEV_LRPPLANCONF');
END;
/


--changeSet QC-5463:14 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_DROP('LRP_PLAN_CONFIG' ,'FK_READONLYSEV_LRPPLANCONFIG');
END;
/
 

--changeSet QC-5463:15 stripComments:false
-- 2a) delete the 10 level records 
DELETE FROM ref_lrp_config_sev WHERE lrp_config_sev_db_id = 10 AND lrp_config_sev_cd = 'IGNORE';

--changeSet QC-5463:16 stripComments:false
DELETE FROM ref_lrp_config_sev WHERE lrp_config_sev_db_id = 10 AND lrp_config_sev_cd = 'NONCRITC';

--changeSet QC-5463:17 stripComments:false
DELETE FROM ref_lrp_config_sev WHERE lrp_config_sev_db_id = 10 AND lrp_config_sev_cd = 'CRITICAL';

--changeSet QC-5463:18 stripComments:false
DELETE FROM ref_lrp_config_sev WHERE lrp_config_sev_db_id = 10 AND lrp_config_sev_cd = 'HIGHLITE';

--changeSet QC-5463:19 stripComments:false
-- 2b) insert the 0 level 
/***********************************************
** INSERT SCRIPT FOR TABLE "REF_LRP_CONFIG_SEV"
** DATE: 05/29/2008 TIME: 00:00:00
************************************************/
insert into REF_LRP_CONFIG_SEV(LRP_CONFIG_SEV_DB_ID, LRP_CONFIG_SEV_CD, PRIORITY_ORD, DESC_SDESC, DESC_LDESC, HEX_COLOR, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
SELECT 0, 'IGNORE', 4, 'Ignore', 'Events that can be ignored', 'FFFFFF',0, TO_DATE('2008-05-16', 'YYYY-MM-DD'), TO_DATE('2008-05-16', 'YYYY-MM-DD'), 100, 'MXI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REF_LRP_CONFIG_SEV WHERE LRP_CONFIG_SEV_DB_ID = 0 AND LRP_CONFIG_SEV_CD = 'IGNORE');

--changeSet QC-5463:20 stripComments:false
insert into REF_LRP_CONFIG_SEV(LRP_CONFIG_SEV_DB_ID, LRP_CONFIG_SEV_CD, PRIORITY_ORD, DESC_SDESC, DESC_LDESC, HEX_COLOR, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
SELECT 0, 'NONCRITC', 3, 'Non-critical', 'Events that are non-critical', 'FFFF00',0, TO_DATE('2008-05-16', 'YYYY-MM-DD'), TO_DATE('2008-05-16', 'YYYY-MM-DD'), 100, 'MXI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REF_LRP_CONFIG_SEV WHERE LRP_CONFIG_SEV_DB_ID = 0 AND LRP_CONFIG_SEV_CD = 'NONCRITC');

--changeSet QC-5463:21 stripComments:false
insert into REF_LRP_CONFIG_SEV(LRP_CONFIG_SEV_DB_ID, LRP_CONFIG_SEV_CD, PRIORITY_ORD, DESC_SDESC, DESC_LDESC, HEX_COLOR, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
SELECT 0, 'CRITICAL', 2, 'Critical', 'Events that are critical', 'FF0000',0, TO_DATE('2008-05-16', 'YYYY-MM-DD'), TO_DATE('2008-05-16', 'YYYY-MM-DD'), 100, 'MXI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REF_LRP_CONFIG_SEV WHERE LRP_CONFIG_SEV_DB_ID = 0 AND LRP_CONFIG_SEV_CD = 'CRITICAL');

--changeSet QC-5463:22 stripComments:false
insert into REF_LRP_CONFIG_SEV(LRP_CONFIG_SEV_DB_ID, LRP_CONFIG_SEV_CD, PRIORITY_ORD, DESC_SDESC, DESC_LDESC, HEX_COLOR, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
SELECT 0, 'HIGHLITE', 1, 'Highlight', 'Events that are highlighted', '5F9EA0',0, TO_DATE('2009-12-10', 'YYYY-MM-DD'), TO_DATE('2009-12-10', 'YYYY-MM-DD'), 100, 'MXI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REF_LRP_CONFIG_SEV WHERE LRP_CONFIG_SEV_DB_ID = 0 AND LRP_CONFIG_SEV_CD = 'HIGHLITE');

--changeSet QC-5463:23 stripComments:false
-- 2c) Update the child records to reference the new parent records
UPDATE LRP_PLAN_CONFIG
SET ADHOC_SEV_DB_ID = 0
WHERE ADHOC_SEV_DB_ID = 10
AND ADHOC_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:24 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET OVERFLOW_SEV_DB_ID = 0
WHERE OVERFLOW_SEV_DB_ID = 10
AND OVERFLOW_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:25 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET OVERLAP_SEV_DB_ID = 0
WHERE OVERLAP_SEV_DB_ID = 10
AND OVERLAP_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:26 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET DURLESSMIN_SEV_DB_ID = 0
WHERE DURLESSMIN_SEV_DB_ID = 10
AND DURLESSMIN_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:27 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET DURGRTMAX_SEV_DB_ID = 0
WHERE DURGRTMAX_SEV_DB_ID = 10
AND DURGRTMAX_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:28 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET OVERDUE_SEV_DB_ID = 0
WHERE OVERDUE_SEV_DB_ID = 10
AND OVERDUE_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:29 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET EXTDEAD_SEV_DB_ID = 0
WHERE EXTDEAD_SEV_DB_ID = 10
AND EXTDEAD_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:30 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET PLANBFOREMINYD_SEV_DB_ID = 0
WHERE PLANBFOREMINYD_SEV_DB_ID = 10
AND PLANBFOREMINYD_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:31 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET PLANAFTMAXYD_SEV_DB_ID = 0
WHERE PLANAFTMAXYD_SEV_DB_ID = 10
AND PLANAFTMAXYD_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:32 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET OUTOFSEQ_SEV_DB_ID = 0
WHERE OUTOFSEQ_SEV_DB_ID = 10
AND OUTOFSEQ_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:33 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET UPDATEACTUAL_SEV_DB_ID = 0
WHERE UPDATEACTUAL_SEV_DB_ID = 10
AND UPDATEACTUAL_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:34 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET EXTRACTEXC_SEV_DB_ID = 0
WHERE EXTRACTEXC_SEV_DB_ID = 10
AND EXTRACTEXC_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:35 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET PRIOREFFECTIVEDT_SEV_DB_ID = 0
WHERE PRIOREFFECTIVEDT_SEV_DB_ID = 10
AND PRIOREFFECTIVEDT_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:36 stripComments:false
UPDATE LRP_PLAN_CONFIG
SET READONLY_SEV_DB_ID = 0
WHERE READONLY_SEV_DB_ID = 10
AND READONLY_SEV_CD in ('IGNORE', 'NONCRITC', 'CRITICAL', 'HIGHLITE');

--changeSet QC-5463:37 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
-- 3) Reintroduce the constraint
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_ADHOCSEV_LRPPLANCONFIG" FOREIGN KEY ("ADHOC_SEV_DB_ID","ADHOC_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:38 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_OVERFLOWSEV_LRPPLANCONFIG" FOREIGN KEY ("OVERFLOW_SEV_DB_ID","OVERFLOW_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:39 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_OVERLAPSEV_LRPPLANCONFIG" FOREIGN KEY ("OVERLAP_SEV_DB_ID","OVERLAP_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:40 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_DURLESSMINSEV_LRPPLANCONFIG" FOREIGN KEY ("DURLESSMIN_SEV_DB_ID","DURLESSMIN_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:41 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_DURGRTMAXSEV_LRPPLANCONFIG" FOREIGN KEY ("DURGRTMAX_SEV_DB_ID","DURGRTMAX_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:42 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_OVERDUESEV_LRPPLANCONFIG" FOREIGN KEY ("OVERDUE_SEV_DB_ID","OVERDUE_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:43 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_EXTDEADSEV_LRPPLANCONFIG" FOREIGN KEY ("EXTDEAD_SEV_DB_ID","EXTDEAD_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:44 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_PLANBFOREMINYDSEV_LRPPLANCO" FOREIGN KEY ("PLANBFOREMINYD_SEV_DB_ID","PLANBFOREMINYD_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:45 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_PLANAFTMAXYDSEV_LRPPLANCONF" FOREIGN KEY ("PLANAFTMAXYD_SEV_DB_ID","PLANAFTMAXYD_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:46 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_OUTOFSEQSEV_LRPPLANCONF" FOREIGN KEY ("OUTOFSEQ_SEV_DB_ID","OUTOFSEQ_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:47 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_UPDATEACTSEV_LRPPLANCONF" FOREIGN KEY ("UPDATEACTUAL_SEV_DB_ID","UPDATEACTUAL_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:48 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_EXTRACTEXCSEV_LRPPLANCONF" FOREIGN KEY ("EXTRACTEXC_SEV_DB_ID","EXTRACTEXC_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:49 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_PREFFECTDTSEV_LRPPLANCONF" FOREIGN KEY ("PRIOREFFECTIVEDT_SEV_DB_ID","PRIOREFFECTIVEDT_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/

--changeSet QC-5463:50 stripComments:true endDelimiter:\n\s*/\s*\n|\n\s*/\s*$
BEGIN
   UTL_MIGR_SCHEMA_PKG.TABLE_CONSTRAINT_ADD('ALTER TABLE "LRP_PLAN_CONFIG" ADD CONSTRAINT "FK_READONLYSEV_LRPPLANCONFIG" FOREIGN KEY ("READONLY_SEV_DB_ID","READONLY_SEV_CD") REFERENCES "REF_LRP_CONFIG_SEV" ("LRP_CONFIG_SEV_DB_ID","LRP_CONFIG_SEV_CD")  DEFERRABLE' );
END;
/