--liquibase formatted sql


--changeSet aopr_hist_comp_rmvl_basic_v1:1 stripComments:false
CREATE OR REPLACE FORCE VIEW aopr_hist_comp_rmvl_basic_v1 
AS
SELECT
   fleet,
   operator,
   ac_reg,
   ac_pn,
   ac_sn,
   pn,
   vendor_code,
   sn,
   pn_description,
   rmvl_date,
   scheduled,
   rmvl_reason_description,
   root_pn,
   root_sn,
   ata_chapter,
   ata_section,
   tsi,
   csi,
   last_install_date,
   ro_number,
   last_ro,
   pn_in,
   sn_in,
   fault_code,
   days_since_install,
   po_number,
   fault_description,
   fault_corrective_action,
   deferral_class,
   deferral_ref,
   departure_airport,
   arrival_airport,
   flight_number,
   mechanic,
   inspector,
   wo_order,
   wo_order_name,
   jic_code,
   last_received_condition,
   'Legacy' AS sourcesystem
FROM
   opr_rbl_hist_comp_removal
-- legacy data
UNION ALL
-- to Maintenix data
SELECT
   assmbl_cd,
   carrier_cd,
   ac_reg_cd,
   ac_pn,
   ac_sn,
   rmvd_pn,
   manufact_cd,
   serial_no_oem,
   rmd_partdescription,
   rmvl_dt,
   spec2k_remove_reason_cd,
   remove_reason_cd,
   root_name,
   root_sn,
   ata_chapter,
   ata_section,
   tsi,
   csi,
   last_install_date,
   ro_number,
   last_ro,
   pn_in,
   sn_in,
   fault_code,
   days_since_install,
   po_number,
   fault_description,
   action_description,
   deferral_class,
   deferral_reference,
   departure_airport,
   arrival_airport,
   flight_number,
   mechanic,
   inspector,
   work_package_number,
   work_package_name,
   jic_code,
   last_received_condition,
   'Maintenix' AS sourcesystem
FROM
   aopr_comp_rmvl_mv1;