delete from EQP_ASSMBL;
delete from REF_WORK_TYPE;
delete from REF_LRP_PRIORITY;
delete from LRP_LOC_CAPABILITY;

-- INSERTING into EQP_ASSMBL
Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'A320',0,'ACFT',null,null,0,26,null,null,null,null,null,'Airbus A319/A320','Airbus A320 aircraft.','30-SEP-99',0,to_date('04-OCT-01','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

-- INSERTING into REF_WORK_TYPE
Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'TURN',null,null,'Turn Check','Turn Check',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'SERVICE',null,null,'Service Check','Service Check(minimum capability)',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'ADMIN',null,null,'Administration work','Administration work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'AIRCOND',null,null,'Air-conditioning system work','Air-conditioning system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'APU',null,null,'Auxiliary Power Unit work','Auxiliary Power Unit work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'AVIONICS',null,null,'Avionics systems work types','Avionics systems work types',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'ELECTRIC',null,null,'Electrical system work','Electrical system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'FUEL',null,null,'Fuel system work','Fuel system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'HANGAR',null,null,'Aircraft hangar visit work','Aircraft hangar visit work(usually for heavy)',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'HYDRAUL',null,null,'Hydraulic circuit work','Hydraulic circuit work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'LINE',null,null,'Line','Line (extensive line including usually A and B checks)',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'OXYGEN',null,null,'Oxygen system work','Oxygen system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'PNEUM',null,null,'Pneumatic system work','Pneumatic system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'PPT',null,null,'Propulsion systems work type','Propulsion systems work type',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'REFINISH',null,null,'Finishing work','Finishing work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'STRUCT',null,null,'Structural work','Structural work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'TRACK',null,null,'Track','Track',0,to_date('13-NOV-01','DD-MON-RR'),to_date('13-NOV-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'WINDOW',null,null,'Window work','Window work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TEST',null,null,'Unit Test',null,2,to_date('21-JAN-05','DD-MON-RR'),to_date('21-JAN-05','DD-MON-RR'),4650,'KRAMER_MASTER');

-- INSERTING into LRP_LOC_CAPABILITY
Insert into REF_LRP_PRIORITY (lrp_priority_db_id, lrp_priority_cd)
values (777, 'HIGH');
Insert into REF_LRP_PRIORITY (lrp_priority_db_id, lrp_priority_cd)
values (777, 'MED');
Insert into REF_LRP_PRIORITY (lrp_priority_db_id, lrp_priority_cd)
values (777, 'LOW');

-- INSERTING into LRP_LOC_CAPABILITY
Insert into LRP_LOC_CAPABILITY (LOC_DB_ID,LOC_ID,LRP_DB_ID,LRP_ID,ASSMBL_DB_ID,ASSMBL_CD,WORK_TYPE_DB_ID,WORK_TYPE_CD,LRP_PRIORITY_DB_ID,LRP_PRIORITY_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000001,4650,81,5000000,'A320',10,'AVIONICS',10,'MED',0,to_date('22-SEP-08','DD-MON-RR'),to_date('22-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_LOC_CAPABILITY (LOC_DB_ID,LOC_ID,LRP_DB_ID,LRP_ID,ASSMBL_DB_ID,ASSMBL_CD,WORK_TYPE_DB_ID,WORK_TYPE_CD,LRP_PRIORITY_DB_ID,LRP_PRIORITY_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000001,4650,81,5000000,'A320',10,'ADMIN',10,'MED',0,to_date('22-SEP-08','DD-MON-RR'),to_date('22-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into LRP_LOC_CAPABILITY (LOC_DB_ID,LOC_ID,LRP_DB_ID,LRP_ID,ASSMBL_DB_ID,ASSMBL_CD,WORK_TYPE_DB_ID,WORK_TYPE_CD,LRP_PRIORITY_DB_ID,LRP_PRIORITY_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000001,4650,81,5000000,'A320',10,'AIRCOND',10,'MED',0,to_date('22-SEP-08','DD-MON-RR'),to_date('22-SEP-08','DD-MON-RR'),4650,'slevert');

