-- cleaning up the db
delete from ref_task_class;
delete from ref_task_subclass;
delete from ref_work_type;

-- INSERTING into EQP_ASSMBL
Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'A320',0,'ACFT',null,null,0,26,null,null,null,null,null,'Airbus A319/A320','Airbus A320 aircraft.','30-SEP-99',0,to_date('04-OCT-01','DD-MON-RR'),to_date('01-APR-04','DD-MON-RR'),4650,'MXMATRIX_DEV');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (8000000,'B767-200',0,'ACFT',null,null,0,26,null,null,null,null,null,'Boeing 767-200',null,null,0,to_date('12-APR-01','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'MX41COREM8');

-- INSERTING into EQP_ASSMBL_BOM
Insert into EQP_ASSMBL_BOM (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_BOM_ID,NH_ASSMBL_DB_ID,NH_ASSMBL_CD,NH_ASSMBL_BOM_ID,BOM_CLASS_DB_ID,BOM_CLASS_CD,CFG_SLOT_STATUS_DB_ID,CFG_SLOT_STATUS_CD,LOGCARD_FORM_DB_ID,LOGCARD_FORM_CD,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,POS_CT,ASSMBL_BOM_CD,ASSMBL_BOM_FUNC_CD,ASSMBL_BOM_ZONE_CD,ASSMBL_BOM_NAME,MANDATORY_BOOL,RVSM_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'A320',0,null,null,null,0,'ROOT',0,'ACTV',null,null,null,null,null,1,'A320',null,null,'Airbus A319/A320',1,0,0,to_date('30-SEP-99','DD-MON-RR'),to_date('16-OCT-07','DD-MON-RR'),4650,'MX0712_MASTER');

Insert into EQP_ASSMBL_BOM (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_BOM_ID,NH_ASSMBL_DB_ID,NH_ASSMBL_CD,NH_ASSMBL_BOM_ID,BOM_CLASS_DB_ID,BOM_CLASS_CD,CFG_SLOT_STATUS_DB_ID,CFG_SLOT_STATUS_CD,LOGCARD_FORM_DB_ID,LOGCARD_FORM_CD,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,POS_CT,ASSMBL_BOM_CD,ASSMBL_BOM_FUNC_CD,ASSMBL_BOM_ZONE_CD,ASSMBL_BOM_NAME,MANDATORY_BOOL,RVSM_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (8000000,'B767-200',0,null,null,null,0,'ROOT',0,'ACTV',null,null,null,null,null,1,'B767-200',null,null,'Boeing 767-200',1,0,0,to_date('12-APR-01','DD-MON-RR'),to_date('16-OCT-07','DD-MON-RR'),4650,'MX0712_MASTER');

-- INSERTING into TASK_DEFN
Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238174,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238176,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238177,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238178,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238183,1,0,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238184,1,0,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238168,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238169,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238170,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238171,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238172,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238173,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238175,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

-- INSERTING into TASK_TASK
Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values  (4650, 238168, 4650, 6000032, 4650, 238168, 10, 'BLOCK', null, null, 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'OTBNR', 'otbnr', null, null, null, null, 0, 0, 'EFFECTIVE_DT', null, null, null, 4, to_date('04-SEP-08', 'DD-MON-RR'), to_date('04-SEP-08', 'DD-MON-RR'), 1, 60, 0.01, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), null, 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 4650, 238169, 4650, 6000032, 4650, 238169, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'BCNR1', 'bcnr1', null, null, null, null, 0, 0, 'EFFECTIVE_DT', null, null, null, 0, to_date('05-SEP-08', 'DD-MON-RR'), to_date('05-SEP-08', 'DD-MON-RR'), 1, 0, 0.02, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcnr', 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK  (TASK_DB_ID,TASK_ID,ACTV_HR_DB_ID,ACTV_HR_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,TASK_CLASS_DB_ID,TASK_CLASS_CD,TASK_PRIORITY_DB_ID,TASK_PRIORITY_CD,ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_BOM_ID,REPL_ASSMBL_DB_ID,REPL_ASSMBL_CD,REPL_ASSMBL_BOM_ID,TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_ORIGINATOR_DB_ID,TASK_ORIGINATOR_CD,TASK_DEF_STATUS_DB_ID,TASK_DEF_STATUS_CD,BITMAP_DB_ID,BITMAP_TAG,TASK_CD,TASK_NAME,TASK_LDESC,INSTRUCTION_LDESC,ISSUE_ACCOUNT_DB_ID,ISSUE_ACCOUNT_ID,RECURRING_TASK_BOOL,TASK_SCHED_FROM_DB_ID,TASK_SCHED_FROM_CD, TASK_APPL_LDESC,TASK_APPL_SQL_LDESC,TASK_REF_SDESC,EST_DURATION_QT,EFFECTIVE_DT,EFFECTIVE_GDT,ROUTINE_BOOL,FORECAST_RANGE_QT,MIN_PLAN_YIELD_PCT,RESOURCE_SUM_BOOL,TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD,REVISION_ORD,ACTV_DT,ACTV_LDESC,ACTV_REF_SDESC,UNIQUE_BOOL,WORKSCOPE_BOOL,AUTO_COMPLETE_BOOL,LAST_SCHED_DEAD_BOOL,TASK_APPL_EFF_LDESC,ENGINEERING_LDESC,CANCEL_ON_AC_INST_BOOL,CANCEL_ON_ANY_INST_BOOL,CREATE_ON_AC_INST_BOOL,CREATE_ON_ANY_INST_BOOL,SOFT_DEADLINE_BOOL,EXT_KEY_SDESC,TASK_REV_REASON_DB_ID,TASK_REV_REASON_CD,REV_NOTE,REV_HR_DB_ID,REV_HR_ID,REV_DT,BLOCK_CHAIN_SDESC,BLOCK_ORD,INITIAL_BLOCK_BOOL,ON_CONDITION_BOOL,LOCKED_BOOL,LOCKED_HR_DB_ID,LOCKED_HR_ID,LOCKED_DT,PLANNING_TYPE_DB_ID,PLANNING_TYPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values  (4650,238170,4650,6000032,4650,238170,10,'BLOCK',10,'HIGH',5000000,'A320',0,null,null,null,null,null,null,null,0,'ACTV',0,1,'BCNR2','bcnr2',null,null,null,null,0,0,'EFFECTIVE_DT',null,null,null,0,to_date('05-SEP-08', 'DD-MON-RR'),to_date('05-SEP-08', 'DD-MON-RR'),1,0,0.02,0,0,'NA',1,to_date('15-SEP-08', 'DD-MON-RR'),null,null,1,0,1,0,null,null,0,0,0,0,0,null,null,null,null,4650,6000032,to_date('15-SEP-08', 'DD-MON-RR'),'bcnr',2,0,0,0,null,null,null,null, null,0,to_date('15-SEP-08', 'DD-MON-RR'),to_date('15-SEP-08', 'DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK  (TASK_DB_ID,TASK_ID,ACTV_HR_DB_ID,ACTV_HR_ID,TASK_DEFN_DB_ID,TASK_DEFN_ID,TASK_CLASS_DB_ID,TASK_CLASS_CD,TASK_PRIORITY_DB_ID,TASK_PRIORITY_CD,ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_BOM_ID,REPL_ASSMBL_DB_ID,REPL_ASSMBL_CD,REPL_ASSMBL_BOM_ID,TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_ORIGINATOR_DB_ID,TASK_ORIGINATOR_CD,TASK_DEF_STATUS_DB_ID,TASK_DEF_STATUS_CD,BITMAP_DB_ID,BITMAP_TAG,TASK_CD,TASK_NAME,TASK_LDESC,INSTRUCTION_LDESC,ISSUE_ACCOUNT_DB_ID,ISSUE_ACCOUNT_ID,RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC,TASK_APPL_SQL_LDESC,TASK_REF_SDESC,EST_DURATION_QT,EFFECTIVE_DT,EFFECTIVE_GDT,ROUTINE_BOOL,FORECAST_RANGE_QT,MIN_PLAN_YIELD_PCT,RESOURCE_SUM_BOOL,TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD,REVISION_ORD,ACTV_DT,ACTV_LDESC,ACTV_REF_SDESC,UNIQUE_BOOL,WORKSCOPE_BOOL,AUTO_COMPLETE_BOOL,LAST_SCHED_DEAD_BOOL,TASK_APPL_EFF_LDESC,ENGINEERING_LDESC,CANCEL_ON_AC_INST_BOOL,CANCEL_ON_ANY_INST_BOOL,CREATE_ON_AC_INST_BOOL,CREATE_ON_ANY_INST_BOOL,SOFT_DEADLINE_BOOL,EXT_KEY_SDESC,TASK_REV_REASON_DB_ID,TASK_REV_REASON_CD,REV_NOTE,REV_HR_DB_ID,REV_HR_ID,REV_DT,BLOCK_CHAIN_SDESC,BLOCK_ORD,INITIAL_BLOCK_BOOL,ON_CONDITION_BOOL,LOCKED_BOOL,LOCKED_HR_DB_ID,LOCKED_HR_ID,LOCKED_DT,PLANNING_TYPE_DB_ID,PLANNING_TYPE_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values  (4650,238171,4650,6000032,4650,238171,10,'BLOCK',10,'HIGH',5000000,'A320',0,null,null,null,null,null,null,null,0,'ACTV',0,1,'BCNR3','bcnr3',null,null,null,null,0,0, 'EFFECTIVE_DT',null,null,null,0,to_date('05-SEP-08', 'DD-MON-RR'),to_date('05-SEP-08', 'DD-MON-RR'),1,0,0.02,0,0,'NA',1,to_date('15-SEP-08', 'DD-MON-RR'),null,null,1,0,1,0,null,null,0,0,0,0,0,null,null,null,null,4650,6000032,to_date('15-SEP-08', 'DD-MON-RR'),'bcnr',3,0,0,0,null,null,null,null, null,0,to_date('15-SEP-08', 'DD-MON-RR'),to_date('15-SEP-08', 'DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 4650, 238172, 4650, 6000032, 4650, 238172, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'BCR1', 'bcr1', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 200, 0.03, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcr', 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 4650, 238183, 4650, 6000032, 4650, 238183, 0, 'REQ', null, null, 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'REQ-R', 'req-r', null, null, null, null, 1, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 60, null, 0, 0, 'NA', 1, to_date('16-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('16-SEP-08', 'DD-MON-RR'), null, null, 0, 0, 0, null, null, null, null, null, 0, to_date('16-SEP-08', 'DD-MON-RR'), to_date('16-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238173, 4650, 6000032, 4650, 238173, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'BCR2', 'bcr2', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 200, 0.03, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcr', 2, 0, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238184, 4650, 6000032, 4650, 238184, 10, 'BLOCK', null, null, 5000000, 'A320', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'OTB-R', 'otb-r', null, null, null, null, 1, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 200, null, 0, 0, 'NA', 1, to_date('16-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('16-SEP-08', 'DD-MON-RR'), null, 1, 1, 0, 0, null, null, null, null, null, 0, to_date('16-SEP-08', 'DD-MON-RR'), to_date('16-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238175, 4650, 6000032, 4650, 238175, 0, 'REQ', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, 20, 'AD', 0, 'ACTV', 0, 1, 'REQ-NR', 'req-nr', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 4, null, null, 1, 40, 0.05, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 0, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238174, 4650, 6000032, 4650, 238174, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, 20, 'AD', 0, 'ACTV', 0, 1, 'OTBNR2', 'otbnr2', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 3, null, null, 1, 60, 0.03, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), null, 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238176, 4650, 6000032, 4650, 238176, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, 10, 'AFL', 0, 'ACTV', 0, 1, 'BCR2-1', 'bcr2-1', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 120, null, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcr2', 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238177, 4650, 6000032, 4650, 238177, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, 10, 'AFL', 0, 'ACTV', 0, 1, 'BCR2-2', 'bcr2-2', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 120, null, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcr2', 2, 0, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values (4650, 238178, 4650, 6000032, 4650, 238178, 10, 'BLOCK', 10, 'HIGH', 5000000, 'A320', 0, null, null, null, null, null, 10, 'AFL', 0, 'ACTV', 0, 1, 'BCR2-3', 'bcr2-3', null, null, null, null, 0, 0, 'MANUFACT_DT', null, null, null, 0, null, null, 1, 120, null, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'bcr2', 3, 0, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

-- INSERT into TASK_WORK_TYPE
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238168, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238168, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238169, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238169, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238170, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238170, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238171, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238171, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238172, 10,'AIRCOND');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238172, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238183, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238183, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238173, 10,'AIRCOND');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238173, 10,'HANGAR');


insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238184, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238184, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238175, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238175, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238174, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238174, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238176, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238176, 10,'HANGAR');


insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238177, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238177, 1,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238178, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 238178, 1,'HANGAR');

-- INSERTING into TASK_TASK_DEP
Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238176,23069,0,'CRT',4650,238177,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238177,23070,0,'CRT',4650,238178,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238178,23071,0,'CRT',4650,238176,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238183,23075,0,'CRT',4650,238183,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238184,23076,0,'CRT',4650,238184,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238169,23065,0,'CRT',4650,238170,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238170,23066,0,'CRT',4650,238171,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238172,23067,0,'CRT',4650,238173,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238173,23068,0,'CRT',4650,238172,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

-- INSERTING into REF_TASK_CLASS
Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'CHECK',0,79,'Check','Collector for Aircraft (used to manage a grouping of task) and infers and aircraft release.',0,0,0,'BLOCK',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'RO',0,81,'Repair/Work Order','Collector for non-aircraft repair work (used to manage a grouping of task).',0,0,0,'BLOCK',0,0,to_date('04-SEP-01','DD-MON-RR'),to_date('04-SEP-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'REPL',0,76,'Replacement','This is a set of RMVL, INST and any ancilliary actions.',1,1,0,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'MOD',0,78,'Part Transformation','Due to maintenance action, part number has been changed',1,1,0,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'OVHL',0,78,'Overhaul','Due to maintenance action, life limits reset',1,1,0,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'CORR',0,76,'Corrective Action','Collector for all corrective actions associated with a fault',0,0,1,'REQ',0,0,to_date('04-SEP-01','DD-MON-RR'),to_date('04-SEP-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'DISCARD',0,46,'Discard','Certificate of Destruction',1,1,0,'REQ',0,0,to_date('26-APR-06','DD-MON-RR'),to_date('26-APR-06','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'REQ',0,120,'Requirement','A requirement is a collection of granular maintenance items making up a maintenance action ',1,1,0,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'INSP',0,77,'Inspection','An inspection type task identifies preventive maintenance action.',0,0,1,'JIC',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'JIC',0,77,'Job Instruction Card','Job Instruction Card.',0,0,1,'JIC',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'ADHOC',0,77,'Ad-Hoc Task','Ad-Hoc Task',0,0,1,'ADHOC',0,0,to_date('14-SEP-07','DD-MON-RR'),to_date('14-SEP-07','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'MPC',0,77,'Master Panel Card','Master Panel Card',0,0,1,'MPC',0,0,to_date('22-FEB-08','DD-MON-RR'),to_date('22-FEB-08','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'BLOCK',0,1,'Block','Block of Requirements',1,1,0,'BLOCK',0,0,to_date('24-JUL-04','DD-MON-RR'),to_date('24-JUL-04','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'CLEAN',0,76,'Cleaning','A task to clean equipment.',0,0,1,'JIC',0,0,to_date('23-SEP-05','DD-MON-RR'),to_date('23-SEP-05','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'CLOSE',0,74,'Close','A task to close up a panel or area after work.',0,0,1,'JIC',0,0,to_date('23-SEP-05','DD-MON-RR'),to_date('23-SEP-05','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'INST',0,74,'Install','A task to install an item onto an aircraft or module.',0,0,1,'JIC',0,0,to_date('23-SEP-05','DD-MON-RR'),to_date('23-SEP-05','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'OPEN',0,75,'Open','A task to open up a panel or area for work.',0,0,1,'JIC',0,0,to_date('23-SEP-05','DD-MON-RR'),to_date('23-SEP-05','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'REF',0,77,'Reference Document','Reference Document',1,1,0,'REF',0,0,to_date('03-JAN-08','DD-MON-RR'),to_date('29-JAN-08','DD-MON-RR'),4650,'MX0803_MASTER');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'REP',0,83,'Approved Repair','A repair task identifies that the work needed to bring component in service will require physical alteration of a component.',0,0,1,'JIC',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'RMVL',0,75,'Removal','A task to remove an item from an aircraft or module.',0,0,1,'JIC',0,0,to_date('23-SEP-05','DD-MON-RR'),to_date('23-SEP-05','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'SRVC',0,76,'Servicing','This task indicates an operational service against equipment',0,0,1,'JIC',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'TEST',0,59,'Test/Adjustment','A testing task identifies that a component needs to be tested before it is identified as serviceable.',0,0,1,'JIC',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TEST',0,1,'Unit Test',null,0,0,0,null,0,2,to_date('20-JAN-05','DD-MON-RR'),to_date('20-JAN-05','DD-MON-RR'),4650,'KRAMER_MASTER');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TSTFLGHT',0,121,'Test Flight','Test Flight',0,0,1,'REQ',0,0,to_date('18-OCT-01','DD-MON-RR'),to_date('07-OCT-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'WARRANTY',0,42,'Warranty','Task required to make Warranty claims',0,0,1,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('07-OCT-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

-- INSERTING into REF_TASK_SUBCLASS
Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'MPCOPEN',0,'MPC',0,77,'Open Master Panel Card','Open Master Panel Card','OPEN',0,to_date('28-FEB-08','DD-MON-RR'),to_date('28-FEB-08','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'MPCCLOSE',0,'MPC',0,77,'Close Master Panel Card','Close Master Panel Card','CLOSE',0,to_date('28-FEB-08','DD-MON-RR'),to_date('28-FEB-08','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'A-CHECK',0,'CHECK',0,79,'A-Check','A-Check','A-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'AMOC',0,'INSP',0,77,'Alternate Means of Compliance','Alternate Means of Compliance','AMOC',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'B-CHECK',0,'CHECK',0,79,'B-Check','B-Check','B-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'C-CHECK',0,'CHECK',0,79,'C-Check','C-Check','C-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'CLEAN',10,'SRVC',0,74,'Cleaning','Cleaning','CLEAN',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'COND',0,'INSP',0,77,'Conditional Inspection','Conditional Inspection','COND',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'D-CHECK',0,'CHECK',0,79,'D-Check','D-Check','D-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'DEBRIEF',0,'INSP',0,77,'Pilot/Crew Debrief',' Pilot/Crew Debrief','DEBRIEF',0,to_date('14-DEC-01','DD-MON-RR'),to_date('14-DEC-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'FIP',0,'CORR',0,77,'Fault Isolation Procedure','Fault Isolation Procedure','FIP',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'FUNCTION',10,'TEST',0,77,'Functional Test','Functional Test','FUNCTION',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'H-CHECK',0,'CHECK',0,79,'H-Check','H-Check','H-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'LUBE',10,'SRVC',0,74,'Lubrication','Lubrication','LUBE',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'NDI',0,'INSP',0,77,'Non-Destructive Inspection','Non-Destructive Inspection','NDI',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'NDT',10,'TEST',0,77,'Non-Destructive Inspection','Non-Destructive Inspection','NDT',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'OPER',10,'TEST',0,77,'Operational Test','Operational Test','OPER',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'PAINT',10,'SRVC',0,74,'Painting','Painting','PAINT',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'POL',10,'SRVC',0,74,'Fuelling and Lubrication','Fuelling and Lubrication','POL',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'RESTORE',10,'REP',0,77,'Restoration','Restoration','RESTORE',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'S-CHECK',0,'CHECK',0,79,'S-Check','S-Check','S-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'SWINST',0,'REPL',0,74,'Software Installation','Software Installation','SWINST',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'VISUAL',0,'INSP',0,77,'Visual Inspection/Check','Visual Inspection/Check','VISUAL',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'W-CHECK',0,'CHECK',0,79,'W-Check','W-Check','W-CHECK',0,to_date('29-OCT-02','DD-MON-RR'),to_date('29-OCT-02','DD-MON-RR'),100,'MXI');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (100,'HT',10,'SRVC',0,77,'Hard TIme',null,'HT',0,to_date('06-APR-01','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (100,'ST',10,'SRVC',0,77,'Soft Time',null,'ST',0,to_date('06-APR-01','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'TEST',0,'INSP',0,1,'Unit Test',null,'TEST',0,to_date('20-JAN-05','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (3000101,'SV',0,'RO',0,1,'Shop Visit','Shop Visit','SV',0,to_date('24-JAN-06','DD-MON-RR'),to_date('21-NOV-06','DD-MON-RR'),4650,'MX0612_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'ACC',0,'INSP',0,75,'ACCEPTANCE CHECK',null,'ACC',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'CAL',0,'INSP',0,75,'CALIBRATION',null,'CAL',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'INS',0,'INSP',0,75,'INSPECTION',null,'INS',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'MTC',0,'INSP',0,75,'MAINTENANCE CHECK',null,'MTC',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'PS',0,'INSP',0,75,'PLANNED SAMPLE',null,'PS',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'REP',10,'SRVC',0,75,'REPAIR',null,'REP',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'RMV',10,'SRVC',0,75,'REMOVAL',null,'RMV',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'SC',0,'INSP',0,75,'SHOP CHECK',null,'SC',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'SP',10,'SRVC',0,75,'SPECIAL PROCESS',null,'SP',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'TPC',0,'INSP',0,75,'TIRE PRESSURE CHECK',null,'TPC',0,to_date('18-MAR-00','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

Insert into REF_TASK_SUBCLASS (TASK_SUBCLASS_DB_ID,TASK_SUBCLASS_CD,TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,USER_SUBCLASS_CD,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (5000000,'TSM',0,'INSP',0,142,'Troubleshooting Manual',null,'TSM',0,to_date('28-OCT-99','DD-MON-RR'),to_date('27-SEP-05','DD-MON-RR'),4650,'MAINTENIX_MASTER');

-- INSERTING into REF_WORK_TYPE

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,WORK_TYPE_ORD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'ADMIN',10, null,null,'Administration work','Administration work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,WORK_TYPE_ORD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'AIRCOND',20, null,null,'Air-conditioning system work','Air-conditioning system work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,WORK_TYPE_ORD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'HANGAR',1, null,null,'Aircraft hangar visit work','Aircraft hangar visit work(usually for heavy)',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

-- INSERTING into TASK_SCHED_RULE
Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238168,0,21,15,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238172,0,21,5,0,0,0,0,5,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238173,0,21,5,0,0,0,0,5,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238183,100,2,10,0,0,0,0,5,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238184,100,2,5,0,0,0,0,10,0,to_date('16-SEP-08','DD-MON-RR'),to_date('16-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238175,100,2,5,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238176,100,2,5,0,0,0,0,15,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238177,100,2,5,0,0,0,0,15,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238178,100,2,5,0,0,0,0,15,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238169,0,21,10,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238170,0,21,10,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238171,0,21,10,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,238174,0,21,13,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

