-- cleaning up the db
delete from ref_task_class;
delete from ref_task_subclass;
delete from ref_work_type;
delete from eqp_assmbl;
delete from eqp_assmbl_bom;
delete from task_defn;
delete from task_task;
delete from task_task_dep;

-- Task Classes
Insert into REF_TASK_CLASS (TASK_CLASS_DB_ID,TASK_CLASS_CD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,AUTO_COMPLETE_BOOL,UNIQUE_BOOL,WORKSCOPE_BOOL,CLASS_MODE_CD,NR_EST_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (0,'REQ',0,120,'Requirement','A requirement is a collection of granular maintenance items making up a maintenance action ',1,1,0,'REQ',0,0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

-- INSERTING into REF_WORK_TYPE
Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,WORK_TYPE_ORD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'ADMIN',10, null,null,'Administration work','Administration work',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into REF_WORK_TYPE (WORK_TYPE_DB_ID,WORK_TYPE_CD,WORK_TYPE_ORD,BITMAP_DB_ID,BITMAP_TAG,DESC_SDESC,DESC_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (10,'HANGAR',1, null,null,'Aircraft hangar visit work','Aircraft hangar visit work(usually for heavy)',0,to_date('23-MAR-01','DD-MON-RR'),to_date('23-MAR-01','DD-MON-RR'),100,'MXI');

Insert into EQP_ASSMBL (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_CLASS_DB_ID,ASSMBL_CLASS_CD,LOGBOOK_TYPE_DB_ID,LOGBOOK_TYPE_CD,BITMAP_DB_ID,BITMAP_TAG,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,AUTHORITY_DB_ID,AUTHORITY_ID,ASSMBL_NAME,ASSMBL_MDESC,PROG_VER_LDESC,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'B767-200',0,'ACFT',null,null,0,26,null,null,null,null,null,'Boeing 767-200',null,null,0,to_date('12-APR-01','DD-MON-RR'),to_date('16-JUL-02','DD-MON-RR'),4650,'slevert');

-- INSERTING into EQP_ASSMBL_BOM
Insert into EQP_ASSMBL_BOM (ASSMBL_DB_ID,ASSMBL_CD,ASSMBL_BOM_ID,NH_ASSMBL_DB_ID,NH_ASSMBL_CD,NH_ASSMBL_BOM_ID,BOM_CLASS_DB_ID,BOM_CLASS_CD,CFG_SLOT_STATUS_DB_ID,CFG_SLOT_STATUS_CD,LOGCARD_FORM_DB_ID,LOGCARD_FORM_CD,IETM_DB_ID,IETM_ID,IETM_TOPIC_ID,POS_CT,ASSMBL_BOM_CD,ASSMBL_BOM_FUNC_CD,ASSMBL_BOM_ZONE_CD,ASSMBL_BOM_NAME,MANDATORY_BOOL,RVSM_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,'B767-200',0,null,null,null,0,'ROOT',0,'ACTV',null,null,null,null,null,1,'B767-200',null,null,'Boeing 767-200',1,0,0,to_date('12-APR-01','DD-MON-RR'),to_date('16-OCT-07','DD-MON-RR'),4650,'slevert');


-- INSERTING into TASK_DEFN
Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_DEFN (TASK_DEFN_DB_ID,TASK_DEFN_ID,LAST_REVISION_ORD,NEW_REVISION_BOOL,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1001,1,0,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

-- INSERTING BLOCKS into TASK_TASK
Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values  (4650, 1000, 4650, 6000032, 4650, 1000, 10, 'REQ', null, null, 4650, 'B767-200', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'MOD-1','MOD-1', null, null, null, null, 0, 0, 'EFFECTIVE_DT', null, null, null, 4, to_date('04-SEP-08', 'DD-MON-RR'), to_date('04-SEP-08', 'DD-MON-RR'), 1, 60, 0.01, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'BLOCK CHAIN', 1, 1, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

Insert into TASK_TASK  (TASK_DB_ID, TASK_ID, ACTV_HR_DB_ID, ACTV_HR_ID, TASK_DEFN_DB_ID, TASK_DEFN_ID, TASK_CLASS_DB_ID, TASK_CLASS_CD, TASK_PRIORITY_DB_ID, TASK_PRIORITY_CD, ASSMBL_DB_ID, ASSMBL_CD, ASSMBL_BOM_ID, REPL_ASSMBL_DB_ID, REPL_ASSMBL_CD, REPL_ASSMBL_BOM_ID, TASK_SUBCLASS_DB_ID, TASK_SUBCLASS_CD, TASK_ORIGINATOR_DB_ID, TASK_ORIGINATOR_CD, TASK_DEF_STATUS_DB_ID, TASK_DEF_STATUS_CD, BITMAP_DB_ID, BITMAP_TAG, TASK_CD, TASK_NAME, TASK_LDESC, INSTRUCTION_LDESC, ISSUE_ACCOUNT_DB_ID, ISSUE_ACCOUNT_ID, RECURRING_TASK_BOOL, TASK_SCHED_FROM_DB_ID, TASK_SCHED_FROM_CD, TASK_APPL_LDESC, TASK_APPL_SQL_LDESC, TASK_REF_SDESC, EST_DURATION_QT, EFFECTIVE_DT, EFFECTIVE_GDT, ROUTINE_BOOL, FORECAST_RANGE_QT, MIN_PLAN_YIELD_PCT, RESOURCE_SUM_BOOL, TASK_MUST_REMOVE_DB_ID, TASK_MUST_REMOVE_CD, REVISION_ORD, ACTV_DT, ACTV_LDESC, ACTV_REF_SDESC, UNIQUE_BOOL, WORKSCOPE_BOOL, AUTO_COMPLETE_BOOL, LAST_SCHED_DEAD_BOOL, TASK_APPL_EFF_LDESC, ENGINEERING_LDESC, CANCEL_ON_AC_INST_BOOL, CANCEL_ON_ANY_INST_BOOL, CREATE_ON_AC_INST_BOOL, CREATE_ON_ANY_INST_BOOL, SOFT_DEADLINE_BOOL, EXT_KEY_SDESC, TASK_REV_REASON_DB_ID, TASK_REV_REASON_CD, REV_NOTE, REV_HR_DB_ID, REV_HR_ID, REV_DT, BLOCK_CHAIN_SDESC, BLOCK_ORD, INITIAL_BLOCK_BOOL, ON_CONDITION_BOOL, LOCKED_BOOL, LOCKED_HR_DB_ID, LOCKED_HR_ID, LOCKED_DT, PLANNING_TYPE_DB_ID, PLANNING_TYPE_ID, RSTAT_CD, CREATION_DT, REVISION_DT, REVISION_DB_ID, REVISION_USER)
values ( 4650, 1001, 4650, 6000032, 4650, 1001, 10, 'REQ', 10, 'HIGH', 4650, 'B767-200', 0, null, null, null, null, null, null, null, 0, 'ACTV', 0, 1, 'REQ-1','REQ-1', null, null, null, null, 0, 0, 'EFFECTIVE_DT', null, null, null, 0, to_date('05-SEP-08', 'DD-MON-RR'), to_date('05-SEP-08', 'DD-MON-RR'), 1, 0, 0.02, 0, 0, 'NA', 1, to_date('15-SEP-08', 'DD-MON-RR'), null, null, 1, 0, 1, 0, null, null, 0, 0, 0, 0, 0, null, null, null, null, 4650, 6000032, to_date('15-SEP-08', 'DD-MON-RR'), 'BLOCK CHAIN', 2, 0, 0, 0, null, null, null, null, null, 0, to_date('15-SEP-08', 'DD-MON-RR'), to_date('15-SEP-08', 'DD-MON-RR'), 4650, 'slevert');

-- INSERTING into TASK_TASK_DEP
Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000,23069,0,'CRT',4650,1001,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_TASK_DEP (TASK_DB_ID,TASK_ID,TASK_DEP_ID,TASK_DEP_ACTION_DB_ID,TASK_DEP_ACTION_CD,DEP_TASK_DEFN_DB_ID,DEP_TASK_DEFN_ID,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1001,23070,0,'CRT',4650,1001,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

-- INSERTING into TASK_SCHED_RULE
Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1000,0,21,15,0,0,0,0,null,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');

Insert into TASK_SCHED_RULE (TASK_DB_ID,TASK_ID,DATA_TYPE_DB_ID,DATA_TYPE_ID,DEF_INTERVAL_QT,DEF_NOTIFY_QT,DEF_DEVIATION_QT,DEF_PREFIXED_QT,DEF_POSTFIXED_QT,DEF_INITIAL_QT,RSTAT_CD,CREATION_DT,REVISION_DT,REVISION_DB_ID,REVISION_USER)
values (4650,1001,0,21,5,0,0,0,0,5,0,to_date('15-SEP-08','DD-MON-RR'),to_date('15-SEP-08','DD-MON-RR'),4650,'slevert');


-- WORK TYPES
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 1000, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 1000, 10,'HANGAR');

insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 1001, 10,'ADMIN');
insert into TASK_WORK_TYPE (TASK_DB_ID,TASK_ID,WORK_TYPE_DB_ID,WORK_TYPE_CD)
values  (4650, 1001, 10,'HANGAR');




